{
  "hash": "210fbcdc946b4cae336588e6c58af610",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"September 2026 Assessment developments\"\nsubtitle: \"Eastern Bering Sea walleye pollock\"\nauthor:\n  - name: James Ianelli\n    corresponding: true\n    orcid: 0000-0002-7170-8677\n    email: jim.ianelli@noaa.gov\n    affiliation:\n      - name: Alaska Fisheries Science Center\n        city: Seattle\n        state: WA\n  - name: Sophia Wassermann\n  - name: Carey McGilliard\n  - name: Grant Adams\n  - name: Matt Cheng\n  - name: Cody Szuwalski\n  - name: Cole Monnahan\nlang: en-US\nbibliography: references.bib\nlink-citations: true\nexecute:\n  echo: false\n  warning: false\n  message: false\nformat:\n  html:\n    css: EBSpollock_Sept_2026.css\n    include-after-body: author-metadata-accessibility.html\n    toc: true\n    toc-depth: 3\n    toc-title: \"Contents\"\n    toc-location: left\n    number-sections: true\n  pdf:\n    documentclass: scrreprt\n    papersize: letter\n    pdf-engine: lualatex\n    latex-tinytex: false\n    toc: true\n    toc-depth: 3\n    number-sections: true\n    fig-cap-location: bottom\n    tbl-cap-location: top\n    geometry:\n      - top=0.86in\n      - bottom=0.82in\n      - left=0.82in\n      - right=0.82in\n      - headheight=16pt\n      - headsep=18pt\n      - footskip=28pt\n    header-includes:\n      - \\input{EBSpollock_Sept_2026-pdf-header.tex}\nlightbox: true\nresources:\n  - scripts/model-26-0/*.R\n  - data/EBSpollock_Sept_2026/model-26-0/model_26_0_retrospective_new_data_inventory.csv\n  - data/EBSpollock_Sept_2026/model-26-0/model_26_0_retrospective_data_block_deletion.csv\n  - data/EBSpollock_Sept_2026/model-26-0/model_26_0_retrospective_data_cumulative_addition.csv\n  - data/EBSpollock_Sept_2026/model-26-0/model_26_0_retrospective_data_reproduction_check.csv\n  - data/EBSpollock_Sept_2026/model-26-0/model_23_0_vs_23_2_admb_trajectories.csv\n  - data/EBSpollock_Sept_2026/model-26-0/model_23_0_vs_23_2_admb_summary.csv\n  - data/EBSpollock_Sept_2026/model-26-0/model_23_0_vs_23_2_admb_provenance.csv\n  - data/EBSpollock_Sept_2026/model-26-0/model_23_2_vs_26_0_selectivity.csv\n  - data/EBSpollock_Sept_2026/model-26-0/model_26_0_index_series_sensitivity_summary.csv\n  - data/EBSpollock_Sept_2026/model-26-0/model_26_0_index_series_sensitivity_trajectories.csv\n  - data/EBSpollock_Sept_2026/model-26-0/model_26_0_sparsenuts_diagnostic_summary.csv\n  - data/EBSpollock_Sept_2026/model-26-0/model_26_0_sparsenuts_chain_diagnostics.csv\n  - data/EBSpollock_Sept_2026/model-26-0/model_26_0_sparsenuts_run_manifest.csv\n  - data/EBSpollock_Sept_2026/model-26-0/model_26_0_sparsenuts_slowest_parameters.csv\n  - data/EBSpollock_Sept_2026/model-26-0/model_26_0_sparsenuts_uncertainty_comparison.csv\n  - data/EBSpollock_Sept_2026/model-26-0/model_26_0_sparsenuts_uncertainty_summary.csv\n  - data/EBSpollock_Sept_2026/model-26-0/model_26_0_script_manifest.csv\n  - data/EBSpollock_Sept_2026/model-26-0/model_26_0_observation_continuity_inventory.csv\n  - data/EBSpollock_Sept_2026/model-26-0/model_26_0_observation_continuity_schedule.csv\n  - data/EBSpollock_Sept_2026/model-26-0/model_26_0_case_deletion_manifest.csv\n  - data/EBSpollock_Sept_2026/model-26-0/model_26_0_case_deletion_summary.csv\n  - data/EBSpollock_Sept_2026/model-26-0/model_26_0_case_deletion_run_manifest.csv\n  - data/EBSpollock_Sept_2026/acronym_glossary.csv\n---\n\n<!--\nEditorial writing note for this document:\n- Use plain language and define necessary scientific terms at first use.\n- Replace jargon and unexplained abbreviations with familiar wording.\n- State results, limits, and next steps in affirmative terms.\n- Preserve specialized terms when they carry a precise scientific meaning.\n-->\n\n::: {.callout-note title=\"AI-assisted development\"}\nArtificial intelligence (AI) tools were used to aid document development and\nmodel implementation. AI-assisted material was reviewed and revised by the\nauthors, who retain responsibility for the scientific content, code, analyses,\ninterpretations, and conclusions.\n:::\n\n::: {.callout-note title=\"Suggested citation\"}\nIanelli, James, Sophia Wassermann, Carey McGilliard, Grant Adams, Matt Cheng,\nCody Szuwalski, and Cole Monnahan. 2026. *September 2026 Assessment\nDevelopments: Eastern Bering Sea Walleye Pollock.* Seattle, WA: Alaska\nFisheries Science Center, National Marine Fisheries Service.\n<https://noaa-afsc.github.io/EBS_pollock/doc/EBSpollock_Sept_2026.html>.\n:::\n\n# Summary\n\nThis working paper brings together eastern Bering Sea pollock assessment work\nthat resumed after the 2025 funding lapse and federal furlough. It establishes\na common review record for data preparation, model numbering, software\ntranslations, diagnostics, projections, and responses to Scientific and\nStatistical Committee (SSC) comments. The comparisons use the 1964--2024 data\nbasis inherited from accepted Model 23.0. New 2025 and 2026 observations will\nenter the assessment after the source products, sample sizes, ageing-error\ntreatment, and quality-control checks are complete.\n\nThe model numbering plan separates scientific purpose from software. Model\n23.0 is the accepted 2024 ADMB assessment model. Model 23.1 is the direct RTMB\ntranslation check, and Model 23.2 is the Rceattle translation check. Model 25.0\nis the RTMB development line begun in 2025, and Model 26.0 is the Rceattle\ndevelopment line begun in 2026. SPoRC provides a supporting comparison across\nthe development lines. The Data section also separates two age-data questions:\nuse of FT-NIRS predicted ages and revision of the method used to expand BTS age\nsamples into annual proportions at age.\n\nModel 25.0 reproduces the corrected full-age BTS ADMB bridge and supports\ncontinued evaluation of composition fit, selectivity, and retrospective\nstability. From 1978 through 2024, the matched Model 23.0 and Model 23.2 ADMB\nruns have correlations of 0.994 for spawning biomass and 0.999 for age-1\nrecruitment; their 2024 differences are +1.12% and -9.19%, respectively. The\nsimple Model 26.0 Rceattle fit met the stated convergence\ncriteria and closely followed the Model 23.2 Rceattle-aligned ADMB bridge, with\ntrajectory correlations above 0.998. Its composition residuals varied less\nthan expected under the fitted model. Forty-seven of 50 dispersed-start fits\nreturned to the best solution, while three reached the same higher objective.\nThe repeated higher objective indicates a recurring alternative solution. All\n50 simulated-data self-tests completed with convergence status OK. The lag-preserving\nnine-peel retrospective produced Mohn's rho values of 0.329 for spawning\nbiomass, 0.211 for total biomass, 0.185 for age-1 recruitment, and -0.126 for\nfishing mortality. The peels generally estimated greater biomass and\nrecruitment and lower fishing mortality than the full fit over the same years.\nControlled data tests for the 2020-to-2021 peel transition identified the 2021\nBTS biomass index as the strongest single influence on spawning biomass, with\nthe 2020 fishery age composition and 2021 BTS age composition also contributing\nto the revision.\nThese results make composition fit, the recurring alternative solution, and\nretrospective stability the principal Model 26.0 evaluation priorities.\n\nThe whole-index-fleet sensitivities retained CPUE and removed BTS, ATS, or AVO\nin separate refits. All three completed with convergence status OK and\npositive-definite Hessians. BTS had the greatest influence: its removal reduced\n2024 spawning biomass by 12.2% and increased 2024 fishing mortality by 98.7%.\nRemoving ATS increased 2024 spawning biomass by 11.7% and age-1 recruitment by\n34.3%. Removing AVO changed each 2024 quantity by less than 7%. These severe\ndeletion tests show the complementary roles of the survey series and identify\nBTS as the principal source of scale information.\n\nThe `spmR` projections demonstrate a reproducible handoff from Model 26.0 to\nthe standard seven-alternative projection workflow. Updated 2025 and 2026 data\nwill provide the basis for ABC, OFL, and status determinations during the\nNovember and December 2026 review cycle. The exploratory recruitment analysis\nfavored the model containing age-0 late-summer sea-surface temperature; its\nnegative fitted pathway provides a testable in-sample association for further\nbiological and predictive evaluation. The bridge, convergence tests,\ndiagnostics, retrospective evaluation, index sensitivities, and projection\nhandoff support the recommendation that Model 26.0 be adopted for 2026\nmanagement advice after the updated-data run and formal Plan Team and SSC\nreview. Model 23.0 provides continuity through that transition. Appendix 1\npreserves the SSC comments and response plan, Appendix 2 provides the\ndevelopment framework for an Ecosystem and Socioeconomic Profile, and\nAppendices 3--6 document the exploratory SparseNUTS run, reproducible model\nworkflow, observation continuity and case-deletion influence, and acronym\nglossary. Appendix 7 documents fishery length-frequency patterns.\n\n# Introduction\n\nThis document brings together eastern Bering Sea pollock assessment work\naffected by the 2025 funding lapse and federal furlough. Routine SAFE\npreparation, review, and archiving paused during that period. After work\nresumed, data preparation and model development progressed on different\nschedules. This report restores a single review record for the data updates,\nmodel numbering, ADMB-to-RTMB bridge, and 2026 RTMB and Rceattle development.\n\nThe main report is organized around the decisions needed for the 2026 review.\nThe **Model specifications** section defines the model numbers and their roles\nso results can be traced to the correct scientific configuration. The **Data**\nsection summarizes the shared assessment inputs and identifies age-data issues\nthat need consistent treatment across platforms. The **Model results** section\npresents the translation checks, Model 26.0 fit and diagnostics, retrospective\nevaluation, sensitivities, projections, and exploratory recruitment pathways\nneeded to judge readiness for assessment use. The **Conclusion** brings that\nevidence together and states the recommended role and next steps for Model\n26.0 during the November and December review cycle.\n\nThe appendices preserve supporting material that informs this work.\n[Appendix 1](#sec-ssc-comments) presents the main SSC comments and planned\nresponses and retains the earlier 2024 comments. [Appendix\n2](#sec-esp-development-framework) provides the development structure for an\nEBS pollock Ecosystem and Socioeconomic Profile (ESP). [Appendix\n3](#sec-sparsenuts) reports exploratory SparseNUTS sampling, [Appendix\n4](#sec-model-run-methods) records the reproducible model workflow, [Appendix\n5](#sec-observation-influence) evaluates observation continuity and\ncase-deletion influence, and [Appendix 6](#sec-glossary) defines the report's\nacronyms. [Appendix 7](#sec-length-frequency-patterns) summarizes seasonal and\nspatial patterns in the observed pollock length-frequency samples. Together,\nthe main sections and appendices connect the resumed work with the assessment\nreview record.\n\n# Model specifications\n\n## Model numbering plan\n\nThe model number should identify the model's place in the review record. The\nsoftware name should be shown separately. Under this plan, **Model 23.0** is the\n2024 ADMB source, **Model 23.1** is its direct RTMB translation check, and\n**Model 23.2** is the Rceattle translation check. The newer model names are\n**Model 25.0 (RTMB)** for the work begun in 2025 and **Model 26.0 (Rceattle)**\nfor the development line begun in 2026.\nThe flowchart shows the two numbered development lines and SPoRC's supporting\ncomparison role (@fig-model-numbering).\n\n```{mermaid}\n%%| label: fig-model-numbering\n%%| fig-cap: \"Proposed numbering and development history for EBS pollock assessment models.\"\n%%| fig-alt: \"Flowchart beginning with the Model 23.0 ADMB source used in 2024. One branch passes through the Model 23.1 RTMB translation check to Model 25.0 in RTMB, begun in 2025. A second branch passes through the Model 23.2 Rceattle translation check to Model 26.0 in Rceattle, begun in 2026. SPoRC supports comparisons with both development lines and would receive a model number if advanced as an assessment candidate.\"\n%%| fig-width: 6.6\n\nflowchart LR\n  accTitle: EBS pollock assessment model numbering and development history\n  accDescr: Flowchart from the 2024 Model 23.0 ADMB source through the Model 23.1 RTMB translation check to the Model 25.0 RTMB line, and through the Model 23.2 Rceattle translation check to the Model 26.0 Rceattle line, with SPoRC supporting comparisons of the two development lines.\n  A[\"Model 23.0<br/>2024 ADMB source\"] -->|\"direct translation<br/>and checks\"| B[\"Model 23.1<br/>RTMB translation check\"]\n  B --> C[\"Model 25.0<br/>RTMB line begun in 2025\"]\n  A -->|\"Rceattle bridge<br/>and checks\"| E[\"Model 23.2<br/>Rceattle translation check\"]\n  E --> D[\"Model 26.0<br/>Rceattle line begun in 2026\"]\n  S[\"SPoRC<br/>supporting comparison\"] -.->|\"common tests\"| C\n  S -.->|\"common tests\"| D\n  classDef model fill:#e8f0f7,stroke:#52616b,color:#111111\n  classDef comparison fill:#fff4cc,stroke:#9a8444,color:#111111\n  class A,B,C,D,E model\n  class S comparison\n```\n\nThe labels should be used as follows:\n\n- **Model 23.0 (ADMB)** identifies the accepted source model used in 2024.\n- **Model 23.1 (RTMB)** identifies the direct translation used to check that the\n  new code reproduces Model 23.0. Its role is a numbered translation check,\n  while Model 23.0 continues to support management advice.\n- **Model 23.2 (Rceattle)** identifies the Rceattle translation check aligned\n  with the modified ADMB bridge. It provides the direct reference for Model\n  26.0 implementation checks.\n- **Model 25.0 (RTMB)** is the public name for the RTMB assessment line begun in\n  2025 at the SSC's request.\n- **Model 26.0 (Rceattle)** is the public name for the Rceattle development line\n  begun in 2026. List its scientific changes separately from the software\n  change. Its bridge, diagnostics, retrospective behavior, and projections\n  support the recommendation for its 2026 operational role. Model 23.0 provides\n  continuity through the formal review transition.\n- **SPoRC** remains a supporting comparison. The [single-region EBS pollock\n  vignette](https://chengmatt.github.io/SPoRC/dev/articles/f_single_region_ebs_pollock_case_study.html)\n  illustrates the bridge from Model 23.0 to SPoRC and identifies the current\n  differences between the implementations. Research on pollock movement and\n  connections between U.S. and Russian waters is progressing. A numbered model\n  name would apply when SPoRC advances as an assessment candidate.\n\nFor later variants, keep the main number and add a decimal suffix, such as\n26.1 or 26.2. Each suffix should represent one clearly documented change. Use\nthe same label in the report, tables, presentations, run folders, and archive.\n\n# Data\n\n## Data summary {#sec-data-summary}\n\nThe current cross-platform comparison uses the sex-combined, ages 1--15 data\nbasis inherited from the 2024 Model 23.0 assessment. The population time series\nextends from 1964 through 2024. Fishery age compositions extend through 2023\nbecause of the normal processing lag. The same underlying assessment\nobservations are translated into the ADMB, RTMB, SPoRC, and Rceattle input\nstructures. Each model retains its own fit calculations, sample-size\nconventions, and data organization. The accepted assessment and\n2024 model-evaluation documents provide the overall data lineage\n[@ianelli2023a; @ianelli2024].\n\nThe basic data used across the platforms are:\n\n- **Fishery data:** annual retained catch from 1964 through 2024, fishery age\n  compositions from 1964 through 2023, empirical fishery weight at age, and\n  the historical fishery catch-per-unit-effort (CPUE) index for 1965--1976.\n- **Bottom-trawl survey (BTS):** the biomass index and its covariance,\n  age compositions, sample sizes, and survey weight at age for 42 survey years\n  during 1982--2024. The standard survey was absent in 2020. Model-based\n  estimation of pollock survey indices and age compositions is described by\n  @OLeary2020, and spatially structured estimation of pollock weight at age is\n  described by @indivero2023.\n- **Acoustic-trawl survey (ATS):** pollock abundance indices, age compositions,\n  sample sizes, and weight at age for 19 survey years during 1994--2024. The\n  survey series includes separate information for age-1 pollock and older\n  pollock. Survey methods are documented by @honkalehto2015; current work on\n  uncertainty in acoustic-trawl estimates is described by @urmy2025.\n- **Supplementary abundance indices:** the acoustic vessel-of-opportunity\n  (AVO) series has 18 observations during 2006--2024, and the historical CPUE\n  series has 12 observations during 1965--1976. The AVO approach and recent\n  reanalysis are described by @honkalehto2011 and @lauffenburger2024.\n- **Biological schedules:** the models use ageing-error information, maturity,\n  natural mortality, and spawning, fishery, and survey weight-at-age schedules.\n  AFSC pollock ageing methods and data quality are summarized by\n  @matta2026agegrowth; spatial and temporal variation in EBS pollock weight at\n  age is evaluated by @indivero2023.\n\nAcross platforms, **ADMB Model 23.0** provides the accepted 2024 assessment\nreference, observation schedule, and source-model settings. **RTMB Models 23.1\nand 25.0** use the corrected ADMB bridge inputs directly and preserve the\ncomplete ages 1--15 BTS composition treatment.\n\nThe summary above describes the common 2024-terminal bridge used for model\ncomparison. New 2025 and 2026 observations will enter the assessment only\nafter their source products, sample sizes, ageing-error treatment, and quality\ncontrol have been finalized.\n\n## Issues {#sec-age-data-issues}\n\nThis section documents two distinct age-composition product issues considered after the 2024\nassessment: the method used to assign ages to individual otoliths and the\nspatio-temporal method used to expand BTS age samples into annual proportions\nat age. The first concerns traditional microscope ages (TMA) versus ages\npredicted by Fourier-transform near-infrared spectroscopy (FT-NIRS). The\nsecond concerns replacement of the prior BTS age-composition estimator with a\ntinyVAST implementation. In the second case, the survey observations remain\nthe same; the estimated annual age-composition data product derived from those\nobservations has changed because the expansion method was revised. These\nchanges occur at different stages of the data workflow and should be evaluated\nseparately.\n\n### FTNIRS age-data {#sec-ftnirs-age-data}\n\nThe Alaska Fisheries Science Center's Age and Growth Program has produced more\nthan 460,000 walleye pollock age estimates since 1971. From 2005 through 2024,\nannual production averaged 11,141 pollock ages and ranged from 8,408 to 14,441.\nAcross Alaska pollock stocks, inter-reader precision was relatively high: the\noverall average coefficient of variation was 4.28%, percent agreement was\n68.6%, and reader and tester estimates generally differed by one year or less\nyear. Eighty percent of pollock aged by the program were 3--10 years old, and\nthe maximum observed age was 31 years. Radiometric analysis supports the\naccuracy of the program's ageing criteria through age 8, while marginal\nincrement analyses, year-class tracking, hard-structure comparisons, and\ncaptive-rearing studies provide additional corroboration. Older ages occur\nmore frequently in the Bering Sea and Aleutian Islands than in the Gulf of\nAlaska, and Bering Sea pollock generally grow more slowly but attain greater\nlengths and ages. Female pollock also become larger at age than males beginning\nat approximately age 5 [@matta2026agegrowth, pp. 33--42]. These production and\nprecision statistics summarize AFSC pollock ageing across Alaska stocks rather\nthan the eastern Bering Sea alone; the eastern Bering Sea assessment is the\nmost data-rich pollock assessment.\n\nThese results describe traditional microscope ageing (TMA), which assigns age\nby preparing an otolith and visually counting annual growth zones. FT-NIRS is\nbeing developed as a rapid secondary ageing method that depends on reference\nages produced through traditional microscopic examination\n[@matta2026agegrowth]. FT-NIRS measures the wavelengths and amount of\nnear-infrared light absorbed by an otolith and predicts age from its spectral\nand chemical signal using a calibration model. It can process otoliths\nsubstantially faster, but its predicted ages are methodologically different\nfrom direct microscope readings ([NOAA Fisheries age-method\noverview](https://www.fisheries.noaa.gov/feature-story/age-and-growth-homework-determining-how-old-fish-are)). The established scale, precision, and\ncorroboration of the TMA series therefore provide important context for\nevaluating whether FT-NIRS predictions preserve the age structure and cohort\nsignals used by the assessment.\n\nThe 2025 CIE discussion paper compared the two methods using pollock data. For\nthe same design-based BTS abundance-at-age inputs, TMA estimates showed a high\ndegree of cohort consistency, whereas FT-NIRS estimates showed lower cohort\nconsistency; the assessment authors described the consequence of that\ndifference as unresolved. The comparison also identified differences between\nTMA- and FT-NIRS-based proportions at age for the fishery, BTS, and ATS. Model\ntests therefore treated FT-NIRS ages as a separate data source and considered\nboth global and fleet-specific FT-NIRS age-error matrices. See the official\n[FT-NIRS data consistency\ncomparisons](https://noaa-afsc.github.io/EBS_pollock/doc/CIE.html#ft-nirs-data-consistency-comparisons)\nfor the cohort plots, composition comparisons, data coverage, and alternative\nage-error treatments.\n\nThe FT-NIRS issue concerns age assignment and associated ageing error. The BTS\nbridge below concerns the subsequent expansion of age observations across\nspace and time. Its scope is the expansion method; a separate analysis\ncompares TMA with FT-NIRS.\n\n### Impact of revised BTS age-composition estimates {#sec-bts-age-data-bridge}\n\nThis section isolates the effect of replacing the original bottom-trawl\nsurvey (BTS) estimates of proportions at age in `BTSProp.csv` with the revised\nestimates in `tinyVAST_props_new.csv`. The age-composition data product changes\nwhile the underlying survey data remain the same. Both ADMB runs use the\ncomplete 2025 input set and the\nsame model specification, executable, starting parameter file, and tinyVAST\n2025 BTS age-composition estimate. The sensitivity restores the original\n1982-2024 BTS proportion estimates while holding the 2025 tinyVAST row\nconstant. The comparison therefore addresses the historical estimator change.\n\nThe 2024 assessment used the previous spatio-temporal expansion of BTS age\nsamples. The revised series uses an improved implementation in `tinyVAST`, a\nmultivariate spatio-temporal generalized linear mixed-model framework that can\nmodel age groups jointly, share information across locations and years, and\narea-expand predictions to annual abundance and proportions at age\n[@thorson2019spatiotemporalcomposition; @thorson2025tinyvast]. The\n[tinyVAST age-composition expansion\nexample](https://vast-lib.github.io/tinyVAST/articles/web_only/age_composition_expansion.html)\ndocuments this workflow for EBS pollock age data. This methodological update\nchanges the estimated BTS proportions at age supplied to the assessment; the\ncontrolled runs below quantify the resulting assessment-model effect while\nholding the other inputs and model configuration fixed.\n\n\n\nThe controlled input comparison changes the historical BTS age-composition\nproduct while holding the 2025 age composition and every other assessment\ninput constant (@tbl-bts-age-data-contrast).\n\n\n::: {#tbl-bts-age-data-contrast .cell tbl-cap='Controlled input contrast for the revised BTS age-composition product. The 2025 BTS age-composition estimate and all other assessment inputs are identical between runs.'}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"hcatzswrmu\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#hcatzswrmu table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#hcatzswrmu thead, #hcatzswrmu tbody, #hcatzswrmu tfoot, #hcatzswrmu tr, #hcatzswrmu td, #hcatzswrmu th {\n  border-style: none;\n}\n\n#hcatzswrmu p {\n  margin: 0;\n  padding: 0;\n}\n\n#hcatzswrmu .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#hcatzswrmu .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#hcatzswrmu .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#hcatzswrmu .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#hcatzswrmu .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#hcatzswrmu .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hcatzswrmu .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#hcatzswrmu .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#hcatzswrmu .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#hcatzswrmu .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#hcatzswrmu .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#hcatzswrmu .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#hcatzswrmu .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#hcatzswrmu .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#hcatzswrmu .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#hcatzswrmu .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#hcatzswrmu .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#hcatzswrmu .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#hcatzswrmu .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hcatzswrmu .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#hcatzswrmu .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#hcatzswrmu .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#hcatzswrmu .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hcatzswrmu .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#hcatzswrmu .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#hcatzswrmu .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hcatzswrmu .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hcatzswrmu .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#hcatzswrmu .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hcatzswrmu .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#hcatzswrmu .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hcatzswrmu .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#hcatzswrmu .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hcatzswrmu .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#hcatzswrmu .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hcatzswrmu .gt_left {\n  text-align: left;\n}\n\n#hcatzswrmu .gt_center {\n  text-align: center;\n}\n\n#hcatzswrmu .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#hcatzswrmu .gt_font_normal {\n  font-weight: normal;\n}\n\n#hcatzswrmu .gt_font_bold {\n  font-weight: bold;\n}\n\n#hcatzswrmu .gt_font_italic {\n  font-style: italic;\n}\n\n#hcatzswrmu .gt_super {\n  font-size: 65%;\n}\n\n#hcatzswrmu .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#hcatzswrmu .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#hcatzswrmu .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#hcatzswrmu .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#hcatzswrmu .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#hcatzswrmu .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#hcatzswrmu .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#hcatzswrmu .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#hcatzswrmu div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_heading\">\n      <td colspan=\"2\" class=\"gt_heading gt_title gt_font_normal gt_bottom_border\" style>BTS Age-Data Contrast</td>\n    </tr>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"metric\">metric</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"value\">value</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"metric\" class=\"gt_row gt_left\">Historical BTS years replaced</td>\n<td headers=\"value\" class=\"gt_row gt_left\">42</td></tr>\n    <tr><td headers=\"metric\" class=\"gt_row gt_left\">First replaced year</td>\n<td headers=\"value\" class=\"gt_row gt_left\">1982</td></tr>\n    <tr><td headers=\"metric\" class=\"gt_row gt_left\">Last replaced year</td>\n<td headers=\"value\" class=\"gt_row gt_left\">2024</td></tr>\n    <tr><td headers=\"metric\" class=\"gt_row gt_left\">2025 BTS age row held constant</td>\n<td headers=\"value\" class=\"gt_row gt_left\">Yes</td></tr>\n    <tr><td headers=\"metric\" class=\"gt_row gt_left\">Maximum absolute proportion-at-age difference</td>\n<td headers=\"value\" class=\"gt_row gt_left\">0.015778407</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\nThe derived-product comparison uses the `both` region from `BTSProp.csv` as\nthe original estimated series and `tinyVAST_props_new.csv` as the revised\nestimated series\n(@fig-bts-age-input-change). Across the 42 matched survey years, relative\nchanges range from\n-11.9% to\n+54.8%; the largest\nabsolute change is\n1.58 percentage points.\nThe calculation uses the original estimated proportion as the denominator and\ndescribes the revision to the derived age-composition product rather than a\nchange in the survey observations or its influence on model results. The\nrevised 2025 row is excluded because the original file ends in 2024.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Percent change in the estimated BTS proportions at age from the original BTSProp.csv data product to the revised tinyVAST_props_new.csv data product for each matched historical survey year. The underlying survey observations are unchanged. Positive bars indicate a larger tinyVAST estimate and negative bars indicate a smaller tinyVAST estimate. Age 15 is the plus group; the BTS survey was absent in 2020.](EBSpollock_Sept_2026_files/figure-html/fig-bts-age-input-change-1.png){#fig-bts-age-input-change fig-alt='Small-multiple bar chart comparing two age-composition data products derived from the same BTS observations for 42 matched survey years from 1982 through 2024, excluding 2020. Each panel shows relative percent change from the original estimated proportions to the tinyVAST estimates for ages 1 through 15. Bars above zero indicate increases and bars below zero indicate decreases. Changes range from about minus 12 percent to plus 55 percent, with the largest increase at age 12 in 2023.' width=1248}\n:::\n:::\n\n\nBoth runs reached maximum absolute gradients below 0.001. The likelihood\ncomponents in @tbl-bts-age-data-diagnostics document the fits and support a\nstructured contrast between scenarios with different observed BTS age values.\n\n\n::: {#tbl-bts-age-data-diagnostics .cell tbl-cap='ADMB fit diagnostics for the matched 2025 model with tinyVAST BTS proportions and with original BTSProp proportions for 1982-2024. Negative-log-likelihood values diagnose each data version; cross-data model selection requires a common observation set and likelihood definition.'}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"ovanmylehk\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#ovanmylehk table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#ovanmylehk thead, #ovanmylehk tbody, #ovanmylehk tfoot, #ovanmylehk tr, #ovanmylehk td, #ovanmylehk th {\n  border-style: none;\n}\n\n#ovanmylehk p {\n  margin: 0;\n  padding: 0;\n}\n\n#ovanmylehk .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#ovanmylehk .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#ovanmylehk .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#ovanmylehk .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#ovanmylehk .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ovanmylehk .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ovanmylehk .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ovanmylehk .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#ovanmylehk .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#ovanmylehk .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#ovanmylehk .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#ovanmylehk .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#ovanmylehk .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#ovanmylehk .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#ovanmylehk .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#ovanmylehk .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#ovanmylehk .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#ovanmylehk .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#ovanmylehk .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ovanmylehk .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#ovanmylehk .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#ovanmylehk .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#ovanmylehk .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ovanmylehk .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#ovanmylehk .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#ovanmylehk .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ovanmylehk .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ovanmylehk .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#ovanmylehk .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ovanmylehk .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#ovanmylehk .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ovanmylehk .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ovanmylehk .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ovanmylehk .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ovanmylehk .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ovanmylehk .gt_left {\n  text-align: left;\n}\n\n#ovanmylehk .gt_center {\n  text-align: center;\n}\n\n#ovanmylehk .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#ovanmylehk .gt_font_normal {\n  font-weight: normal;\n}\n\n#ovanmylehk .gt_font_bold {\n  font-weight: bold;\n}\n\n#ovanmylehk .gt_font_italic {\n  font-style: italic;\n}\n\n#ovanmylehk .gt_super {\n  font-size: 65%;\n}\n\n#ovanmylehk .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#ovanmylehk .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#ovanmylehk .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#ovanmylehk .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#ovanmylehk .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#ovanmylehk .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#ovanmylehk .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#ovanmylehk .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#ovanmylehk div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_heading\">\n      <td colspan=\"5\" class=\"gt_heading gt_title gt_font_normal gt_bottom_border\" style>BTS Age-Data Bridge Diagnostics</td>\n    </tr>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"scenario\">Data version</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"total_nll\">Total NLL</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"bts_index_nll\">BTS index NLL</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"bts_age_nll\">BTS age NLL</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"maximum_gradient\">Maximum |gradient|</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"scenario\" class=\"gt_row gt_left\">Current tinyVAST BTS ages</td>\n<td headers=\"total_nll\" class=\"gt_row gt_right\">7,062.470</td>\n<td headers=\"bts_index_nll\" class=\"gt_row gt_right\">32.673</td>\n<td headers=\"bts_age_nll\" class=\"gt_row gt_right\">211.608</td>\n<td headers=\"maximum_gradient\" class=\"gt_row gt_right\">4.97&nbsp;×&nbsp;10<sup style='font-size: 65%;'>−4</sup></td></tr>\n    <tr><td headers=\"scenario\" class=\"gt_row gt_left\">Prior BTSProp ages for 1982-2024</td>\n<td headers=\"total_nll\" class=\"gt_row gt_right\">7,061.360</td>\n<td headers=\"bts_index_nll\" class=\"gt_row gt_right\">32.856</td>\n<td headers=\"bts_age_nll\" class=\"gt_row gt_right\">210.849</td>\n<td headers=\"maximum_gradient\" class=\"gt_row gt_right\">2.07&nbsp;×&nbsp;10<sup style='font-size: 65%;'>−4</sup></td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\nThe revision changes terminal spawning biomass by\n-0.415%.\nThe largest spawning-biomass difference is\n0.881%\nin 1985.\nTerminal age-1 recruitment changes by\n-2.015%,\nwhich is the largest recruitment difference in the series. Terminal predicted\ncatch changes by\n+0.016%.\nThe terminal and maximum differences for each assessment quantity are\nsummarized in @tbl-bts-age-data-results.\n\n\n::: {#tbl-bts-age-data-results .cell tbl-cap='Relative effects of replacing the original historical BTS proportions with tinyVAST proportions. Percent differences are tinyVAST minus original, divided by the absolute original estimate.'}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"orwnwqnfek\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#orwnwqnfek table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#orwnwqnfek thead, #orwnwqnfek tbody, #orwnwqnfek tfoot, #orwnwqnfek tr, #orwnwqnfek td, #orwnwqnfek th {\n  border-style: none;\n}\n\n#orwnwqnfek p {\n  margin: 0;\n  padding: 0;\n}\n\n#orwnwqnfek .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#orwnwqnfek .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#orwnwqnfek .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#orwnwqnfek .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#orwnwqnfek .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#orwnwqnfek .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#orwnwqnfek .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#orwnwqnfek .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#orwnwqnfek .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#orwnwqnfek .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#orwnwqnfek .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#orwnwqnfek .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#orwnwqnfek .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#orwnwqnfek .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#orwnwqnfek .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#orwnwqnfek .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#orwnwqnfek .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#orwnwqnfek .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#orwnwqnfek .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#orwnwqnfek .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#orwnwqnfek .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#orwnwqnfek .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#orwnwqnfek .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#orwnwqnfek .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#orwnwqnfek .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#orwnwqnfek .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#orwnwqnfek .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#orwnwqnfek .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#orwnwqnfek .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#orwnwqnfek .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#orwnwqnfek .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#orwnwqnfek .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#orwnwqnfek .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#orwnwqnfek .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#orwnwqnfek .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#orwnwqnfek .gt_left {\n  text-align: left;\n}\n\n#orwnwqnfek .gt_center {\n  text-align: center;\n}\n\n#orwnwqnfek .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#orwnwqnfek .gt_font_normal {\n  font-weight: normal;\n}\n\n#orwnwqnfek .gt_font_bold {\n  font-weight: bold;\n}\n\n#orwnwqnfek .gt_font_italic {\n  font-style: italic;\n}\n\n#orwnwqnfek .gt_super {\n  font-size: 65%;\n}\n\n#orwnwqnfek .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#orwnwqnfek .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#orwnwqnfek .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#orwnwqnfek .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#orwnwqnfek .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#orwnwqnfek .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#orwnwqnfek .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#orwnwqnfek .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#orwnwqnfek div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_heading\">\n      <td colspan=\"5\" class=\"gt_heading gt_title gt_font_normal gt_bottom_border\" style>Effects of tinyVAST Historical BTS Proportions</td>\n    </tr>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"result_quantity\">Quantity</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"result_terminal_year\">Terminal year</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"terminal_percent_difference\">Terminal difference (%)</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"maximum_absolute_percent_difference\">Maximum absolute difference (%)</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"year_of_maximum_difference\">Year of maximum</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"result_quantity\" class=\"gt_row gt_left\">Predicted catch</td>\n<td headers=\"result_terminal_year\" class=\"gt_row gt_right\">2025</td>\n<td headers=\"terminal_percent_difference\" class=\"gt_row gt_right\">0.016</td>\n<td headers=\"maximum_absolute_percent_difference\" class=\"gt_row gt_right\">0.050</td>\n<td headers=\"year_of_maximum_difference\" class=\"gt_row gt_right\">1991</td></tr>\n    <tr><td headers=\"result_quantity\" class=\"gt_row gt_left\">Age-1 recruitment</td>\n<td headers=\"result_terminal_year\" class=\"gt_row gt_right\">2025</td>\n<td headers=\"terminal_percent_difference\" class=\"gt_row gt_right\">−2.015</td>\n<td headers=\"maximum_absolute_percent_difference\" class=\"gt_row gt_right\">3.851</td>\n<td headers=\"year_of_maximum_difference\" class=\"gt_row gt_right\">2024</td></tr>\n    <tr><td headers=\"result_quantity\" class=\"gt_row gt_left\">Spawning biomass</td>\n<td headers=\"result_terminal_year\" class=\"gt_row gt_right\">2025</td>\n<td headers=\"terminal_percent_difference\" class=\"gt_row gt_right\">−0.415</td>\n<td headers=\"maximum_absolute_percent_difference\" class=\"gt_row gt_right\">0.881</td>\n<td headers=\"year_of_maximum_difference\" class=\"gt_row gt_right\">1985</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\nAcross years, spawning-biomass and predicted-catch differences remain small,\nwhile age-1 recruitment shows the larger year-to-year response\n(@fig-bts-age-data-bridge).\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Percent differences in spawning biomass, age-1 recruitment, and predicted catch between the 2025 model using tinyVAST BTS proportions and the sensitivity using original BTSProp proportions for 1982-2024. The horizontal line marks zero difference.](EBSpollock_Sept_2026_files/figure-html/fig-bts-age-data-bridge-1.png){#fig-bts-age-data-bridge fig-alt='Three-panel line graph of percent differences from 1964 through 2025. Spawning-biomass differences remain within one percent and equal minus 0.4 percent in 2025. Recruitment differences remain within four percent and equal minus 2.0 percent in 2025. Predicted-catch differences remain within 0.1 percent.' width=960}\n:::\n:::\n\n\n### Planned 2026 survey-data update {#sec-planned-2026-survey-data}\n\nData from the 2026 Acoustic-Trawl Survey (ATS), along with 2026 AVO data, will\nbe added to this report after processing and quality-control review are\ncomplete. The update will identify any resulting changes to the relevant time\nseries, figures, tables, and model inputs.\n\n\n# Model results\n\n## Model 23.1 {#sec-model-23-1}\n\nThe [September 2025 ADMB-to-RTMB bridge](https://noaa-afsc.github.io/EBS_pollock/doc/Sept_2025.html#bridging-admb-to-rtmb)\ndocumented the small ADMB changes made before checking the direct RTMB\ntranslation. For the model numbering used here, **ADMB original = Model 23.0**\nand **ADMB Modified = Model 23.1**. The second label identifies the adjusted\nADMB version used to build and check Model 23.1 in RTMB. Model 23.1 serves as a\ntranslation check, while Model 23.0 continues to support management advice.\n\nThe spawning biomass and age-1 recruitment comparisons are reproduced in\n@fig-model-23-1-admb-bridge. The source analysis attributes most of the small\ndifferences between the series to a revised rule for fishery selectivity,\nspecifically the penalty applied when selectivity declines after age 6.\n\n![Spawning stock biomass and age-1 recruitment from the original and modified ADMB bridge configurations. ADMB original corresponds to Model 23.0, and ADMB Modified is the adjusted ADMB version used to check Model 23.1.](assets/fig-model-23-1-admb-bridge.png){#fig-model-23-1-admb-bridge fig-alt=\"Two-panel comparison of Models 23.0 and 23.1 from 1978 through 2024. The upper panel shows closely tracking spawning stock biomass trajectories with uncertainty ribbons. The lower panel shows closely tracking age-1 recruitment estimates with uncertainty bars. Model 23.1 is generally slightly above Model 23.0 for spawning biomass, while recruitment differences are small and vary by year.\" width=\"100%\"}\n\n## Model 25.0 {#sec-model-25-0}\n\nThe RTMB implementation matches the corrected ADMB bridge, including the full\nBTS age range, at the same best-fitting ADMB values, called maximum-likelihood\nestimates. Observed and predicted BTS age compositions each cover ages 1--15\nand sum to one. Integer sample sizes set their influence in the multinomial\nlikelihood, the fit calculation for age proportions. The total number of fish\nused to scale the age composition retains its ages 2--15 definition. The\nfitted BTS survey index measures biomass. Comparison with the historical\nconfiguration shows the effect of correcting the treatment of BTS data in the\nmodel fit.\n\nThe same corrected base model supports the one-step-ahead (OSA) checks, the\nanalysis fitted only to BTS data (Only-BTS sensitivity), nine retrospective\npeels that remove recent years in sequence, and stock-production-model (SPM)\nprojections. The retrospective procedure accounts for reporting lags among\ndata streams and uses the previous year's selectivity curve for the final\nyear. Positive Mohn's rho values, which summarize the direction and size of\nretrospective change, identify a stability concern for continued evaluation.\nSimulation testing and review will guide future operational refinements.\nCurrent management advice uses the accepted ADMB assessment model. The\nhierarchical Form-2 results generated with SparseNUTS describe a separate\nselectivity option.\n\n### Evaluation of time-varying BTS availability {#sec-bts-availability}\n\nThis diagnostic isolates the biomass variation induced by the fitted\ntime-varying bottom-trawl survey (BTS) selectivity, the proportion of fish at\neach age available to the survey. It holds population\nabundance and weight at age constant across years. The fixed abundance vector\nfor ages 1--15 is the arithmetic mean of the model-estimated numbers at each\nage across 1982--2024. The fixed weight vector is the mean BTS weight at each\nage across the survey observations. This centers the controlled calculation\non the estimated population age structure over the analysis period while\nremoving annual changes in population abundance.\n\nFor year $t$, the selectivity-only vulnerable biomass is\n\n$$\nB^{\\mathrm{sel}}_t = \\sum_{a=1}^{15} \\bar{N}_a\\,\\bar{w}_a\\,s_{t,a},\n$$\n\nwhere $\\bar{N}_a$ is mean estimated numbers at age across 1982--2024,\n$\\bar{w}_a$ is mean BTS weight at age, and only BTS selectivity $s_{t,a}$\nvaries. This is an availability index rather than an estimated stock biomass\ntrajectory.\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Relative BTS-vulnerable biomass attributable only to fitted annual BTS selectivity. Mean estimated numbers at ages 1–15 across 1982–2024 and mean BTS weight at age are held fixed. Values are divided by the 1982–2024 mean; the dashed horizontal line marks that mean.](EBSpollock_Sept_2026_files/figure-html/fig-bts-selectivity-only-biomass-1.png){#fig-bts-selectivity-only-biomass fig-alt='Line plot from 1982 through 2024 showing the BTS vulnerable-biomass variation attributable to fitted annual selectivity when mean estimated numbers and mean weight at age are held fixed.' width=960}\n:::\n:::\n\n\nWith numbers and weights fixed, the selectivity-only index in\n@fig-bts-selectivity-only-biomass ranges from\n54.4% to\n139.1% of its period mean.\nThus, fitted BTS selectivity alone produces deviations of approximately\n-45.6% to\n39.1% around mean\nvulnerable biomass. This range describes changes in modeled survey\navailability caused by selectivity. Population biomass change is outside this\ncontrolled calculation.\n\nAn analogous weight-only calculation holds mean estimated numbers at age and\nBTS selectivity fixed. Selectivity is averaged at each age over 1982--2024,\nwhile the observed BTS weight-at-age vector varies among the 42 survey years.\nThe 2020 survey was absent, so the plotted BTS weight series moves directly\nfrom 2019 to 2021.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Relative BTS-vulnerable biomass attributable only to annual BTS weight at age. Mean estimated numbers at ages 1–15 across 1982–2024 and mean 1982–2024 BTS selectivity at age are held fixed. Values are divided by the mean across the 42 BTS observation years; the dashed horizontal line marks that mean.](EBSpollock_Sept_2026_files/figure-html/fig-bts-weight-only-biomass-1.png){#fig-bts-weight-only-biomass fig-alt='Line plot over the 42 BTS observation years from 1982 through 2024 showing the vulnerable-biomass variation attributable to annual weight at age when mean estimated numbers and mean selectivity at age are held fixed; the series moves from 2019 to 2021 because the 2020 survey was absent.' width=960}\n:::\n:::\n\n\nWith mean estimated numbers at age and mean selectivity fixed, annual BTS\nweights alone produce the relative vulnerable-biomass range shown in\n@fig-bts-weight-only-biomass, from\n80.8% to\n124.5%, equivalent\nto deviations of\n-19.2% to\n24.5% around\nthe mean.\n\nThe third calculation holds both BTS selectivity and BTS weight at age at\ntheir period means and varies only the model-estimated numbers at ages 1--15.\nIt therefore describes how the estimated population age structure and scale\nwould change BTS-vulnerable biomass under a constant observation process.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Relative BTS-vulnerable biomass attributable only to annual estimated numbers at ages 1–15. Mean BTS selectivity at age and mean BTS weight at age are held fixed. Values are divided by the 1982–2024 mean; the dashed horizontal line marks that mean.](EBSpollock_Sept_2026_files/figure-html/fig-bts-numbers-only-biomass-1.png){#fig-bts-numbers-only-biomass fig-alt='Line plot from 1982 through 2024 showing a numbers-at-age-only BTS vulnerable-biomass index ranging from about 0.48 to 1.53.' width=960}\n:::\n:::\n\n\nWith mean selectivity and mean weight fixed, estimated numbers at age alone\nproduce the relative vulnerable-biomass range shown in\n@fig-bts-numbers-only-biomass, from\n48.1% to\n152.7%, equivalent\nto deviations of\n-51.9% to\n52.7% around\nthe mean. Unlike the first two controlled calculations, this third series\nreflects estimated population change rather than observation-process\nvariation.\n\nThe combined comparison in @fig-bts-biomass-components-overlay places the\nthree controlled series from @fig-bts-selectivity-only-biomass,\n@fig-bts-weight-only-biomass, and @fig-bts-numbers-only-biomass on the same\nscale as the observed BTS biomass index. Each series is divided by its own\nperiod mean, so 100% represents the mean for that series rather than a common\nbiomass level. The BTS observation series retains the 2020 survey gap.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Relative BTS-vulnerable-biomass components and observed BTS biomass index. The selectivity-only, weight-only, numbers-at-age-only, and observed survey series are each normalized to their own 1982–2024 mean. The dashed horizontal line marks 100%; the observed BTS series moves from 2019 to 2021 because the 2020 survey was absent.](EBSpollock_Sept_2026_files/figure-html/fig-bts-biomass-components-overlay-1.png){#fig-bts-biomass-components-overlay fig-alt='Overlaid time-series plot from 1982 through 2024 comparing normalized BTS vulnerable biomass attributable separately to annual selectivity, annual weight at age, and annual numbers at age with the normalized observed BTS biomass index. Each series has a period mean of 100 percent, and the observed survey line has a gap in 2020.' width=1056}\n:::\n:::\n\n\nThe pairwise display in @fig-bts-biomass-components-pairs removes the time\naxis and compares the four normalized series directly. Diagonal panels show\neach marginal distribution, lower panels show paired annual values, and upper\npanels report Pearson correlations based on the years available for each\npair. These correlations describe shared temporal variation among the\nnormalized indices. The controlled calculations leave causal contributions to\nobserved survey biomass undetermined.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Pairwise relationships among observed BTS biomass and the selectivity-only, weight-at-age-only, and numbers-at-age-only relative indices shown in @fig-bts-biomass-components-overlay. Values are percentages of each series' 1982–2024 mean. Upper panels report Pearson correlations using available paired years.](EBSpollock_Sept_2026_files/figure-html/fig-bts-biomass-components-pairs-1.png){#fig-bts-biomass-components-pairs fig-alt='Pairs-plot matrix for four normalized annual series: observed BTS biomass, selectivity-only vulnerable biomass, weight-at-age-only vulnerable biomass, and numbers-at-age-only vulnerable biomass. Diagonal panels show distributions, lower panels show paired annual points, and upper panels give Pearson correlations.' width=1056}\n:::\n:::\n\n\n\n## Model 26.0 {#sec-model-26-0}\n\n### Data and simple model approach\n\nModel 26.0 uses the common 1964--2024 bridge data described in\n@sec-data-summary. This run was fitted with Rceattle version 5.23.0 from the\n[`dsem-v5-integration` branch](https://github.com/grantdadams/Rceattle/tree/dsem-v5-integration),\npinned at commit\n`adf22f84b399e84e3b9a707e0b3bbb1624179a27`. The version number and commit are\nreported together because the run represents a branch snapshot.\n\nThe simple configuration retains non-parametric selectivity for the fishery,\nacoustic vessel-of-opportunity (AVO), acoustic-trawl survey (ATS), and\nhistorical catch-per-unit-effort series. The bottom-trawl survey (BTS) retains\nthe logistic curve and separate age-1 component used in the bridge. Annual\nselectivity changes follow the established random-walk configuration. The 2D\nage-by-year AR1 formulation remains a separate research sensitivity, allowing\nthis analysis to focus on the simpler assessment structure requested for Model\n26.0.\nThe data-flow diagram shows how the shared observations support the fitted\npopulation states, bridge comparison, diagnostics, projections, and\nenvironmental-pathway analysis (@fig-model-26-approach).\n\nThe Model 26.0 configuration retains ages 1--15, the established selectivity\nforms, and the two-stage fitting sequence (@tbl-model-26-configuration). The\ncurrent branch retains the time-varying parametric BTS field as a compatibility\nsetting and directs future development toward the newer selectivity-linkage\ninterface. This run keeps the compatibility setting to match the bridge\nconfiguration. A later Model 26.x comparison can evaluate the interface change\nseparately.\n\nBoth fitting stages met the current Rceattle convergence criteria. Model 26.0\nhad a maximum absolute gradient of $7.65\\times10^{-5}$, a positive-definite\nHessian, and a Hessian condition number of 489,090. The weakest direction\nremains associated with the shared ATS/AVO annual selectivity changes\n(@tbl-model-26-convergence).\n\nThe analysis is archived as separate R scripts for the\n[assessment fit and OSA checks](scripts/model-26-0/run_model_26_rceattle_5_23.R),\n[DSEM pathways](scripts/model-26-0/run_model_26_dsem_5_23_pathways.R),\n[retrospective analysis](scripts/model-26-0/run_model_26_retrospective_sensitivity_5_23.R),\n[retrospective data sensitivity](scripts/model-26-0/run_model_26_retrospective_data_sensitivity_5_23.R),\n[whole-index-fleet sensitivity](scripts/model-26-0/run_model_26_index_series_sensitivity_5_23.R),\n[spmR projections](scripts/model-26-0/run_model_26_spmr_projection_5_23.R),\nand [self-test](scripts/model-26-0/run_model_26_self_test_5_23.R).\n\n```{mermaid}\n%%| label: fig-model-26-approach\n%%| fig-cap: \"Data and calculation flow for the simple Model 26.0 Rceattle analysis.\"\n%%| fig-alt: \"Fishery catch, survey and abundance indices, age compositions, and biological schedules enter the Rceattle population model. The model estimates annual abundance, recruitment, fishing mortality, and selectivity. The fitted model is then compared with the Model 23.2 bridge and used for OSA residuals, jitter tests, self-tests, whole-index-fleet sensitivities, retrospective analysis, Standard Projection Model projections, and exploratory DSEM pathways.\"\n%%| fig-width: 5.8\n\nflowchart TB\n  accTitle: Simple Model 26.0 data and analysis flow\n  accDescr: A top-to-bottom flowchart shows assessment inputs entering the simple Rceattle population model. Its fitted states support the bridge comparison, diagnostics, projection, and exploratory DSEM analyses.\n  subgraph I[\"Assessment inputs\"]\n    direction TB\n    A[\"Catch and abundance indices\"]\n    B[\"Ages 1-15 composition data\"]\n    C[\"Maturity, mortality, weight,<br/>and ageing error\"]\n  end\n  A --> M[\"Model 26.0<br/>Rceattle 5.23.0\"]\n  B --> M\n  C --> M\n  M --> S[\"Abundance, recruitment,<br/>fishing mortality, selectivity\"]\n  subgraph O[\"Model evaluation and use\"]\n    direction TB\n    V[\"Model 23.2 bridge comparison\"]\n    D[\"OSA, jitter, self-test,<br/>index sensitivity, retrospective\"]\n    P[\"spmR projection\"]\n    E[\"Exploratory DSEM pathways\"]\n  end\n  S --> V\n  S --> D\n  S --> P\n  S --> E\n  classDef input fill:#e8f0f7,stroke:#52616b,color:#111111\n  class A,B,C,M,S,V,D,P,E input\n```\n\n| Item | Model 26.0 setting |\n|---|---|\n| Assessment years and ages | 1964--2024; ages 1--15 |\n| Composition fit | `MultinomialAFSC`; likelihood sample sizes retained from the bridge workbook |\n| Non-parametric selectivity | Fishery, AVO, ATS, and historical CPUE |\n| BTS selectivity | Logistic curve with the separate age-1 component retained from the bridge |\n| Time variation | Established random-walk selectivity changes |\n| Natural mortality | Fixed age schedule used in the bridge |\n| Fitting sequence | Scale fit with annual selectivity changes held constant, followed by the full simple fit |\n\n: Main settings for the Rceattle 5.23.0 Model 26.0 analysis. {#tbl-model-26-configuration}\n\n| Fit | Objective | Maximum gradient | Positive-definite Hessian | Status |\n|---|---:|---:|:---:|:---:|\n| Stage 1 scale fit | 562.952 | 0.0000495 | Yes | OK |\n| Model 26.0 | 716.908 | 0.0000765 | Yes | OK |\n\n: Model 26.0 fitting results from Rceattle 5.23.0. {#tbl-model-26-convergence}\n\n### Model 23.2 bridge comparison\n\nFor this comparison, **Model 23.2** identifies the Rceattle-aligned ADMB bridge\nconfiguration. It contains the structural and likelihood changes needed to\nplace the ADMB and Rceattle calculations on a common basis. Model 23.2 therefore\nprovides the closest reference for evaluating the fitted Model 26.0\ntrajectories, while Model 23.1 continues to identify the direct RTMB translation\ndescribed earlier.\n\nThe matched Model 23.0 and Model 23.2 ADMB runs use the same input selector and\nshared data files. From 1978 through 2024, their spawning biomass trajectories\nhave a correlation of 0.994 and a mean absolute difference of 7.15%. Their\nage-1 recruitment trajectories have a correlation of 0.999 and a mean absolute\ndifference of 3.26%. In 2024, Model 23.2 spawning biomass is 1.12% higher and\nage-1 recruitment is 9.19% lower than Model 23.0. The uncertainty intervals\noverlap broadly across the displayed period (@fig-model-23-0-23-2-admb).\n\nThe three Model 26.0 trajectories have correlations above 0.998 with the Model\n23.2 bridge, and their mean absolute differences range from 0.69% to 1.45%\n(@tbl-model-26-bridge). The fitted trajectories closely follow the bridge over\nthe full assessment period (@fig-model-26-bridge). The remaining differences\nreflect parameter estimation in Rceattle rather than a fixed-parameter\ntranslation test.\n\nThe [annual comparison data](data/EBSpollock_Sept_2026/model-26-0/model_23_0_vs_23_2_admb_trajectories.csv),\n[summary](data/EBSpollock_Sept_2026/model-26-0/model_23_0_vs_23_2_admb_summary.csv),\nand [source record](data/EBSpollock_Sept_2026/model-26-0/model_23_0_vs_23_2_admb_provenance.csv)\npreserve the paired estimates, standard errors, run summaries, and file\nchecksums used for the comparison.\n\n![Spawning biomass and age-1 recruitment from matched ADMB Model 23.0 and Rceattle-aligned ADMB Model 23.2 runs, 1978--2024. Shading and vertical bars show plus or minus two standard errors.](assets/model-26-0/model_23_0_vs_23_2_admb_trajectories.png){#fig-model-23-0-23-2-admb fig-alt=\"Two vertically arranged panels compare Model 23.0 and Model 23.2 from 1978 through 2024. The upper panel shows spawning biomass lines with shaded uncertainty bands; Model 23.2 is generally higher through much of the series, and the estimates converge in recent years. The lower panel shows age-1 recruitment points with vertical uncertainty bars; the two models track closely, with Model 23.2 lower in 2024. Models are distinguished by color, line type, and point shape.\" width=\"100%\"}\n\n| Quantity | Correlation | Mean absolute difference | 2024 difference |\n|---|---:|---:|---:|\n| Spawning biomass | 0.9992 | 1.45% | +2.88% |\n| Age-1 recruitment | 0.9997 | 0.69% | -4.95% |\n| Total biomass | 0.9989 | 1.17% | +1.63% |\n\n: Basic comparison of Model 26.0 with the Model 23.2 Rceattle-aligned ADMB\nbridge. Differences are relative to Model 23.2. {#tbl-model-26-bridge}\n\n![Spawning biomass, age-1 recruitment, and total biomass from Model 26.0 and the Model 23.2 bridge.](assets/model-26-0/model_26_0_bridge_trajectories.png){#fig-model-26-bridge fig-alt=\"Three vertically arranged time-series panels compare Model 26.0 with the Model 23.2 bridge from 1964 through 2024. The two lines closely track for spawning biomass, age-1 recruitment, and total biomass, with small departures in selected years.\" width=\"92%\"}\n\nThe annual selectivity comparisons place Model 23.2 on the left and Model 26.0\non the right. Each curve is divided by its annual maximum, so the figures\ncompare shape rather than scale. Fishery curves cover 1964--2024, BTS curves\ncover 1982--2024, and ATS curves cover 1994--2024. Across the matched ages and\nyears, the normalized curves have correlations of 0.997 for the fishery,\ngreater than 0.999 for BTS, and 0.878 for ATS. The fishery and BTS shapes align\nclosely, while the ATS comparison shows more age-specific differences\n(@fig-model-23-2-26-fishery-selectivity--@fig-model-23-2-26-ats-selectivity).\nThe [selectivity comparison data](data/EBSpollock_Sept_2026/model-26-0/model_23_2_vs_26_0_selectivity.csv)\nretain the unscaled and normalized annual values.\n\n![Annual fishery selectivity for Model 23.2 and Model 26.0, with each curve normalized to a maximum of one.](assets/model-26-0/model_23_2_vs_26_0_fishery_selectivity.png){#fig-model-23-2-26-fishery-selectivity fig-alt=\"Two tall side-by-side ridge plots compare relative fishery selectivity at ages 1 through 15 for every year from 1964 through 2024. Model 23.2 is on the left in blue and Model 26.0 is on the right in green. The annual curves have very similar shapes and track the same changes through time.\" width=\"92%\"}\n\n![Annual bottom-trawl survey selectivity for Model 23.2 and Model 26.0, with each curve normalized to a maximum of one.](assets/model-26-0/model_23_2_vs_26_0_bts_selectivity.png){#fig-model-23-2-26-bts-selectivity fig-alt=\"Two tall side-by-side ridge plots compare relative bottom-trawl survey selectivity at ages 1 through 15 for every year from 1982 through 2024. Model 23.2 is on the left in blue and Model 26.0 is on the right in green. Both sets of curves rise from younger to older ages and align closely across years.\" width=\"92%\"}\n\n![Annual acoustic-trawl survey selectivity at ages 2--15 for Model 23.2 and Model 26.0, with each curve normalized to a maximum of one.](assets/model-26-0/model_23_2_vs_26_0_ats_selectivity.png){#fig-model-23-2-26-ats-selectivity fig-alt=\"Two tall side-by-side ridge plots compare relative acoustic-trawl survey selectivity at ages 2 through 15 for every year from 1994 through 2024. Model 23.2 is on the left in blue and Model 26.0 is on the right in green. Both panels begin at age 2, rise across younger ages, and level across older ages, with visible age-specific differences between the panels.\" width=\"92%\"}\n\n### Diagnostics\n\nThe diagnostic sequence begins with one-step-ahead residuals for composition\ndata, followed by dispersed starting values, simulated-data recovery,\nwhole-index-fleet deletion, and retrospective peels. These tests address\ncomplementary questions: observation fit, sensitivity to starting values,\nrecovery under known simulated data, influence of major survey streams, and\nstability as recent years are removed.\n\n#### One-step-ahead residuals\n\nOne-step-ahead (OSA) residuals compare each observed age proportion with its\nconditional prediction after the preceding age bins have been accounted for.\nRceattle calculated the internal fishery and BTS residuals, and\n[`afscOSA` version 0.0.1](https://github.com/noaa-afsc/afscOSA/releases/tag/v0.0.1)\nproduced the common AFSC plots and summaries. For ATS, `afscOSA` calculated\nthe OSA residuals directly from ages 2--15, the ages that contribute to its\ncomposition likelihood. The `N` input came from the\nRceattle `Sample_size` field used in the multinomial likelihood. It represents\nthe likelihood sample size. The table reports the effective sample size\nseparately.\n\nThe table and figure use the same composition rows retained by the `afscOSA`\ncount conversion. The fishery and BTS retain every input year. ATS age 1 is\nzero in both the observed and fitted compositions, so its composition\nlikelihood and diagnostics begin at age 2. Including the structural-zero\ncolumn in a generic 15-bin residual sequence creates an artificial first\nresidual and shifts the remaining ATS sequence. The corrected conversion uses\nthe 14 contributing ages. ATS 2020 remains in the fitted Rceattle likelihood;\nits sample size of one is distributed among ages 2--15, and every\nage-specific count rounds to zero in the `afscOSA` conversion. The common\ndisplay therefore uses the other 18 ATS years.\n\nEach SDNR is below its expected interval: 0.638 for the fishery, 0.802 for BTS,\nand 0.849 for ATS (@tbl-model-26-osa). The aggregate fits and residual bubbles\nshow the age, year, and cohort locations of the remaining patterns\n(@fig-model-26-osa). Interpretation emphasizes the aggregate fits and cells\nsupported by appreciable predicted counts.\n\n| Composition source | Years displayed | Residuals | SDNR | Expected interval | Likelihood sample-size total | Rounded count total | Effective sample size |\n|---|---:|---:|---:|---:|---:|---:|---:|\n| Fishery | 60 | 840 | 0.638 | 0.952--1.048 | 17,147 | 17,127 | 154,219 |\n| BTS | 42 | 588 | 0.802 | 0.943--1.057 | 5,403 | 5,397 | 3,040 |\n| ATS | 18 | 234 | 0.849 | 0.909--1.091 | 930 | 914 | 680 |\n\n: OSA dispersion and aggregate sample-size diagnostics. SDNR is the standard\ndeviation of normalized residuals. The likelihood sample-size total sums all\nrows used in the fitted Rceattle likelihood, including ATS 2020. The rounded\ncount total and effective sample size come from the displayed `afscOSA`\nconversion.\n{#tbl-model-26-osa}\n\n![Aggregate age-composition fits, OSA quantile plots, and residual bubbles for the fishery, BTS, and ATS. The fishery and BTS panels retain every input year. ATS uses ages 2--15 and retains 18 display years because its sample size of one in 2020 produces zero rounded counts in the plotting conversion.](assets/model-26-0/model_26_0_afscosa.png){#fig-model-26-osa fig-alt=\"Four rows of diagnostic plots for fishery, bottom-trawl survey, and acoustic-trawl survey age compositions. The fishery and bottom-trawl survey panels contain ages 1 through 15 and all input years. The acoustic-trawl survey panels begin at age 2, contain 18 years, and omit 2020 from the display because its sample size of one produces zero rounded counts. The first row compares aggregate observed and fitted proportions. The second row shows OSA quantile plots with residual standard deviations of 0.64 for fishery, 0.80 for bottom-trawl survey, and 0.85 for acoustic-trawl survey. The lower rows show OSA and Pearson residual bubbles by age and year.\" width=\"100%\"}\n\n#### Jitter test\n\nFifty phased refits began from parameter values perturbed with standard\ndeviation 0.2 and seed 20260831. All 50 completed with convergence status OK.\nForty-seven returned to the best objective within 0.001. Three reached the same\nhigher objective, approximately 609.5 units above the best value. The objective\ndistribution and summary count show the 47 returns to the best solution and\nthe three higher-mode fits (@fig-model-26-jitter; @tbl-model-26-jitter). This\nrepeated higher solution identifies a second mode and supports retaining the\ntwo-stage fitting sequence and dispersed-start checks in routine work.\n\n| Requested fits | Converged fits | Returned to best | Higher-mode fits | Largest objective difference |\n|---:|---:|---:|---:|---:|\n| 50 | 50 | 47 | 3 | 609.5 |\n\n: Fifty-start jitter test for Model 26.0. {#tbl-model-26-jitter}\n\n![Distribution of objective differences from the best solution in 50 jitter refits.](assets/model-26-0/model_26_0_jitter_50.png){#fig-model-26-jitter fig-alt=\"Histogram of objective differences for 50 converged jitter fits. Forty-seven values cluster at zero, while three fits occur around 609.5 objective units above the best solution.\" width=\"78%\"}\n\n#### Self-test\n\nThe self-test simulated 50 new observation sets from Model 26.0 and refitted\neach from the original pre-fit starting values. Recruitment deviations were\nheld at their fitted realization, so this test measures recovery under new\nobservation error. All 50 refits completed with convergence status OK; the\nlargest maximum gradient was $1.19\\times10^{-4}$. Recruitment had the widest\ncentral 90% range and the largest mean absolute difference, while total\nbiomass had the narrowest range and smallest mean absolute difference\n(@tbl-model-26-self-test; @fig-model-26-self-test).\n\nThe current simulator redrew some AVO and BTS index observations to retain\npositive values. Those simulated observations follow a positive-truncated\ndistribution while the fitted bridge likelihood uses the corresponding normal\nform. The recovery summary therefore serves primarily as a fitting and coding\ncheck. A future observation-model sensitivity can align the fitted and\nsimulated distributions directly.\n\n| Quantity | Median difference | Mean absolute difference | Central 90% range |\n|---|---:|---:|---:|\n| Age-1 recruitment | -1.51% | 9.76% | -23.76% to +22.83% |\n| Spawning biomass | -2.09% | 6.23% | -13.55% to +17.75% |\n| Total biomass | -1.71% | 4.77% | -9.34% to +13.36% |\n\n: Recovery across all years and the 50 observation-level self-tests.\n{#tbl-model-26-self-test}\n\n![Distribution of differences between self-test refits and the operating Model 26.0 values.](assets/model-26-0/model_26_0_self_test_recovery.png){#fig-model-26-self-test fig-alt=\"Horizontal boxplots show percent differences from the operating-model values for age-1 recruitment, spawning biomass, and total biomass across 50 simulated observation sets and all assessment years. Distributions are centered slightly below zero and are widest for recruitment.\" width=\"82%\"}\n\n#### Whole index-series sensitivity\n\nThree refits tested the influence of the complete BTS, ATS, and AVO fleets.\nEach fit started from the converged Model 26.0 estimates and retained the base\nconfiguration, including the non-parametric selectivity settings, fixed\neffects for recruitment deviations, and CPUE. Setting a fleet's `Fleet_type` to `Off` removes\nits index and composition contributions from the likelihood. The ATS\nsensitivity also removed the separate ATS age-1 index fleet; the BTS age-1\nfleet was already off in the base model. The objective values have different\ndata contributions, so interpretation uses the trajectory changes rather than\nan objective or AIC comparison.\nThe [reproducible sensitivity script](scripts/model-26-0/run_model_26_index_series_sensitivity_5_23.R)\nrecords this configuration.\n\nAll three refits completed with convergence status OK and positive-definite\nHessians. Their maximum gradients ranged from $3.68\\times10^{-5}$ to\n$6.68\\times10^{-5}$. Dropping BTS had the greatest effect on population scale\nand fishing mortality: 2024 spawning biomass decreased 12.2%, total biomass\ndecreased 15.3%, and fishing mortality increased 98.7%. Dropping ATS increased\n2024 spawning biomass 11.7%, total biomass 19.3%, and recruitment 34.3%.\nDropping AVO changed each 2024 quantity by less than 7% (@tbl-model-26-index-sensitivity).\n\nThe trajectories show the strong historical role of BTS and the increasing\nrecent contribution of ATS, while AVO provides a smaller complementary signal\n(@fig-model-26-index-sensitivity). Whole-series deletion is an intentionally\nsevere influence test. The result supports retaining all three survey streams\nand giving particular attention to BTS data preparation and availability in\nthe operational update. The [summary data](data/EBSpollock_Sept_2026/model-26-0/model_26_0_index_series_sensitivity_summary.csv)\nand [annual trajectories](data/EBSpollock_Sept_2026/model-26-0/model_26_0_index_series_sensitivity_trajectories.csv)\nprovide the reported values.\n\n| Sensitivity | Index observations excluded | Composition years excluded | 2024 SSB change | 2024 total biomass change | 2024 recruitment change | 2024 fishing mortality change |\n|---|---:|---:|---:|---:|---:|---:|\n| Drop BTS | 42 | 42 | -12.2% | -15.3% | -4.6% | +98.7% |\n| Drop ATS and ATS age-1 | 37 | 19 | +11.7% | +19.3% | +34.3% | -11.6% |\n| Drop AVO | 18 | 0 | +4.4% | +5.3% | +6.8% | -3.3% |\n\n: Whole-index-fleet sensitivities relative to the Model 26.0 base fit. CPUE was\nretained in every fit. {#tbl-model-26-index-sensitivity}\n\n![Annual changes in spawning biomass, total biomass, age-1 recruitment, and fishing mortality after dropping the complete BTS, ATS, or AVO fleet from Model 26.0.](assets/model-26-0/model_26_0_index_series_sensitivity.png){#fig-model-26-index-sensitivity fig-alt=\"Four line-chart panels show percent changes from the Model 26.0 base fit after dropping BTS, ATS, or AVO. Drop BTS is a blue solid line and produces the largest historical changes, a lower terminal biomass, and nearly double the terminal fishing mortality. Drop ATS is an orange long-dashed line and produces higher recent biomass and recruitment. Drop AVO is a green dot-dashed line and stays closest to the base fit. A horizontal gray line marks zero change.\" width=\"100%\"}\n\n#### Retrospective analysis\n\n##### Configuration and primary results\n\nNine peels ended in 2023 through 2015. The primary analysis follows the\nstream-specific lag rules used in the earlier retrospective analysis. Fishery\nage compositions retain their one-year lag, the ATS age-1 index retains its\ntwo-year lag, and the discontinued CPUE series continues to end in 1976. The\nremaining active index and composition series extend through the peel year when\nan observation exists. All 81 stream-by-peel checks reproduced these rules.\n\nEach peel recalculates its data-based fishery-selectivity starting values and\nuses the same two-stage fitting sequence as the full Model 26.0 fit. The first\nstage establishes population and selectivity scale with annual selectivity\nchanges held constant. The second stage estimates those annual changes. The\nterminal fishery and CPUE selectivity increment is fixed at zero, which carries\nthe preceding-year selectivity-at-age curve into the terminal year. The largest\nterminal-to-preceding-year selectivity difference was\n$6.7\\times10^{-16}$. The\n[retrospective script](scripts/model-26-0/run_model_26_retrospective_sensitivity_5_23.R)\nrecords the lag, convergence, and selectivity checks.\n\nAll nine peels completed with convergence status OK and positive-definite\nHessians. The largest maximum gradient was $2.01\\times10^{-4}$.\n\nThe peels generally estimate greater spawning biomass, total biomass, and\nrecruitment, together with lower fishing mortality, than the full model over\nthe corresponding terminal years. Spawning biomass has the largest Mohn's rho\nand the largest average relative revision, making it a central Model 26.0\nevaluation priority (@tbl-model-26-retro; @fig-model-26-retro).\n\n| Quantity | Mohn's rho |\n|---|---:|\n| Total biomass | 0.211 |\n| Spawning biomass | 0.329 |\n| Age-1 recruitment | 0.185 |\n| Fishing mortality | -0.126 |\n\n: Mohn's rho from nine lag-preserving, two-stage Model 26.0 peels. Each value\ncompares a peel at its terminal assessment year with the corresponding value\nfrom the full Model 26.0 fit. {#tbl-model-26-retro}\n\n![Spawning biomass, total biomass, recruitment, and fishing mortality for Model 26.0 and nine lag-preserving retrospective peels.](assets/model-26-0/model_26_0_retrospective.png){#fig-model-26-retro fig-alt=\"Four line-chart panels show age-1 recruitment, fishing mortality, spawning biomass, and total biomass for the full Model 26.0 fit and nine peels ending from 2023 back to 2015. Earlier peels generally show greater biomass and recruitment and lower fishing mortality over shared years.\" width=\"100%\"}\n\n##### Sensitivity and evaluation\n\nThe data-sensitivity evaluation focuses on the main downward revision between\nthe peels ending in 2020 and 2021. The same stream-specific lag rules identify\nfive newly available observations: the 2020 fishery age composition and the\n2021 BTS biomass index, BTS age composition, AVO index, and BTS age-1 index.\nEach controlled refit starts from the converged 2021-peel estimates, retains\nthe 2021 parameter map, keeps DSEM disabled, and removes one observation block.\nThis design measures the conditional influence of each new data block while\nholding the Model 26.0 structure constant. The\n[data-sensitivity script](scripts/model-26-0/run_model_26_retrospective_data_sensitivity_5_23.R)\nrecords the [observation inventory](data/EBSpollock_Sept_2026/model-26-0/model_26_0_retrospective_new_data_inventory.csv),\n[block-deletion results](data/EBSpollock_Sept_2026/model-26-0/model_26_0_retrospective_data_block_deletion.csv),\n[cumulative-addition results](data/EBSpollock_Sept_2026/model-26-0/model_26_0_retrospective_data_cumulative_addition.csv),\nand [reproduction check](data/EBSpollock_Sept_2026/model-26-0/model_26_0_retrospective_data_reproduction_check.csv).\n\nAll five block-deletion fits and six cumulative-addition fits completed with\nconvergence status OK and positive-definite Hessians; the largest maximum\ngradient was $5.66\\times10^{-5}$. Removing the 2021 BTS biomass index had the\nlargest effect on 2020 spawning biomass, increasing it by 28.2%, and increased\nthe 2013 and 2014 cohort estimates by 11.5% and 15.7%. Removing the 2021 BTS\nage composition increased 2020 spawning biomass by 14.1%, while removing the\n2020 fishery age composition increased the 2013 cohort by 13.6% and 2020\nspawning biomass by 5.7%. The AVO and BTS age-1 index effects on these older\ncohorts and spawning biomass were negligible\n(@tbl-model-26-retro-sensitivity; @fig-model-26-retro-sensitivity).\n\nThe cumulative evaluation begins with the 2021 state and process dimensions\nand the observation availability of the 2020 peel. Adding the 2020 fishery age\ncomposition reduced the 2020 spawning-biomass difference from 46.1% to 28.6%,\nadding the 2021 BTS biomass index reduced it to 13.8%, and adding the 2021 BTS\nage composition brought it to within 0.04% of the complete 2021 peel. The AVO\nand BTS age-1 indices completed the sequence. The final step reproduced the\ncomplete 2021 objective and selected estimates exactly. Together, the removal\nand addition tests identify the fishery age composition and BTS data as the\nprincipal signals associated with this retrospective revision, with the BTS\nbiomass index providing the largest single influence on spawning biomass.\n\n| Data block removed | 2013 cohort change | 2014 cohort change | 2020 SSB change | Maximum gradient |\n|---|---:|---:|---:|---:|\n| 2020 fishery age composition | +13.6% | +5.6% | +5.7% | $4.14\\times10^{-5}$ |\n| 2021 BTS biomass index | +11.5% | +15.7% | +28.2% | $4.04\\times10^{-5}$ |\n| 2021 BTS age composition | +7.6% | +6.0% | +14.1% | $5.66\\times10^{-5}$ |\n| 2021 AVO index | +0.02% | +0.02% | -0.04% | $5.02\\times10^{-5}$ |\n| 2021 BTS age-1 index | 0.0% | 0.0% | 0.0% | $4.83\\times10^{-5}$ |\n\n: Controlled data-block removal from the lag-preserving 2021 peel. Percentages\nshow changes from the complete 2021-peel estimates. {#tbl-model-26-retro-sensitivity}\n\n![Influence of data blocks entering between the lag-preserving 2020 and 2021 peels.](assets/model-26-0/model_26_0_retrospective_data_sensitivity.png){#fig-model-26-retro-sensitivity fig-alt=\"Horizontal grouped bars show changes in the 2013 and 2014 cohort estimates and spawning biomass in 2018 and 2020 after removing one observation block from the 2021 peel. Removing the 2021 BTS biomass index produces the largest increase in 2020 spawning biomass; the 2020 fishery age composition and 2021 BTS age composition also contribute.\" width=\"100%\"}\n\n### Projections\n\nThe projection uses `spmR` version 0.3.0 and the validated Standard Projection\nModel workflow. The\n[projection runner](scripts/model-26-0/run_model_26_spmr_projection_5_23.R)\nand [input writer](scripts/model-26-0/write_spmr_projection_inputs.R) transfer\nthe current Model 26.0 population state, annual recruitment, biological\nschedules, and recent fishing pattern into the `pm.prj` format. The projection\nuses the arithmetic mean fishery selectivity-at-age and fishing mortality from\n2020--2024; mean fishing mortality over those years is 0.1984.\n\n#### Standard alternatives\n\nThe seven alternatives use 1,000 simulations over 14 projection years beginning\nin 2025. Catch is fixed at 1,350 thousand t in 2025 and 2026, so the alternatives\nfirst separate in 2027. These Model 26.0 results are intended to just demonstrate\nthe linkage with the standard Tier 3 projection model. ABC and OFL\nrecommendations and status determinations will be available when the new data\nare updated for the SSC's December 2026 consideration.\n\nThe 2027--2028 comparison keeps spawning biomass at or above the $B_{35\\%}$\nproxy under Alternatives 1--5. Alternative 6 is below the proxy in both years,\nand Alternative 7 moves below it in 2028. Projected catch, ABC, and OFL share\nthe fixed-catch assumptions in 2025 and 2026 and then follow the rules for each\nalternative (@tbl-model-26-projection; @fig-model-26-projection;\n@fig-model-26-projection-removals).\n\n| Alternative | Year | Catch | ABC | OFL | SSB | F | B/B~35%~ |\n|---:|---:|---:|---:|---:|---:|---:|---:|\n| 1 | 2027 | 1,864 | 1,864 | 2,259 | 2,476 | 0.35 | 1.17 |\n| 1 | 2028 | 1,308 | 1,308 | 1,583 | 2,115 | 0.31 | 1.00 |\n| 2 | 2027 | 1,864 | 1,864 | 2,259 | 2,476 | 0.35 | 1.17 |\n| 2 | 2028 | 1,308 | 1,308 | 1,583 | 2,115 | 0.31 | 1.00 |\n| 3 | 2027 | 1,132 | 1,132 | 2,259 | 2,582 | 0.20 | 1.22 |\n| 3 | 2028 | 1,015 | 1,015 | 1,963 | 2,447 | 0.20 | 1.16 |\n| 4 | 2027 | 856 | 856 | 2,259 | 2,619 | 0.15 | 1.24 |\n| 4 | 2028 | 803 | 803 | 2,104 | 2,585 | 0.15 | 1.22 |\n| 5 | 2027 | 0 | 0 | 2,259 | 2,726 | 0.00 | 1.29 |\n| 5 | 2028 | 0 | 0 | 2,455 | 3,035 | 0.00 | 1.44 |\n| 6 | 2027 | 1,561 | 1,561 | 1,561 | 2,017 | 0.37 | 0.95 |\n| 6 | 2028 | 1,210 | 1,210 | 1,210 | 1,831 | 0.34 | 0.87 |\n| 7 | 2027 | 1,509 | 1,809 | 1,809 | 2,211 | 0.32 | 1.05 |\n| 7 | 2028 | 1,424 | 1,424 | 1,424 | 1,977 | 0.36 | 0.94 |\n\n: Model 26.0 `spmR` results for 2027 and 2028. Catch, ABC, OFL, and SSB are\nrounded simulation means in thousand t. {#tbl-model-26-projection}\n\n![Projected spawning biomass under the seven Standard Projection Model alternatives.](assets/model-26-0/model_26_0_spmr_stock_status.png){#fig-model-26-projection fig-alt=\"Seven panels show median projected spawning biomass and central 90-percent intervals from 2025 through 2038. A dashed line marks B35 percent in each panel. The alternatives separate after the fixed-catch years.\" width=\"100%\"}\n\n![Projected catch, ABC, and OFL under the seven Standard Projection Model alternatives.](assets/model-26-0/model_26_0_spmr_removals.png){#fig-model-26-projection-removals fig-alt=\"Seven panels compare projected catch, maximum permissible ABC, and OFL from 2025 through 2038. The lines share the fixed-catch years and then separate according to each alternative.\" width=\"100%\"}\n\n#### Fixed-catch sensitivity\n\nAn additional Alternative 2 run fixes catch at 1,300 thousand t from 2025\nthrough 2032. Mean spawning biomass remains above the $B_{35\\%}$ proxy through\nthe displayed fixed-catch period. The displayed $B/B_{35\\%}$ values remain\nabove one, reaching 1.12 in 2028 and 1.25 in 2032\n(@tbl-model-26-projection-alt2).\n\n| Year | Catch | ABC | OFL | SSB | F | B/B~35%~ |\n|---:|---:|---:|---:|---:|---:|---:|\n| 2025 | 1,300 | 2,360 | 2,878 | 3,523 | 0.180 | 1.67 |\n| 2026 | 1,300 | 2,131 | 2,588 | 3,013 | 0.200 | 1.43 |\n| 2028 | 1,300 | 1,583 | 1,909 | 2,366 | 0.269 | 1.12 |\n| 2030 | 1,300 | 1,460 | 1,786 | 2,447 | 0.308 | 1.16 |\n| 2032 | 1,300 | 1,594 | 1,967 | 2,645 | 0.313 | 1.25 |\n\n: Alternative 2 projection with catch fixed at 1,300 thousand t. Catch, ABC,\nOFL, and SSB are rounded simulation means in thousand t.\n{#tbl-model-26-projection-alt2}\n\n### Exploratory DSEM recruitment pathways\n\nThe Dynamic Structural Equation Model (DSEM) analysis links recruitment to a\nsmall set of prespecified environmental pathways while retaining the Model\n26.0 assessment structure. It uses the same Rceattle 5.23.0 branch snapshot.\nThe four models share the same observation years, missing-value pattern,\nstandardization, and time-series treatment of the two environmental indices.\n\nThe response is age-1 recruitment. Late-summer sea-surface temperature (SST)\nis aligned with the cohort's age-0 year. Cold-pool extent is aligned with the\nfollowing age-1 calendar year. SST represents a broad energetic-condition\npathway, while cold-pool extent represents a possible spatial-separation and\ncannibalism pathway. The conceptual graph keeps the biological steps visible\neven though the fitted examples use direct proxy paths (@fig-model-26-dsem-dag).\n\nAll four DSEM fits completed with positive-definite Hessians and convergence\nstatus OK. Fit AIC favored the DSEM model with age-0 late-summer SST. The\ncombined model was 1.63 AIC units higher, the no-edge reference was 2.25 units\nhigher, and the cold-pool model was 4.11 units higher\n(@fig-model-26-dsem-aic; @tbl-model-26-dsem).\n\nThe SST pathway is negative in both models that include it, with intervals\nbelow zero. The cold-pool pathway is smaller and its interval spans zero in\nboth models (@fig-model-26-dsem-paths; @tbl-model-26-dsem-paths). These results\ndescribe an in-sample association that is consistent with the proposed\nenergetic pathway. Direct measurements of fall age-0 energy, prey quality,\noverwinter survival, and juvenile-adult overlap will provide the stronger next\ntests of the biological mechanism.\n\nThe diagnostics and DSEM results support continued Model 26.0 development.\nThe close bridge trajectories and complete convergence provide a strong\nimplementation basis. The OSA dispersion, repeated higher jitter mode, and\npositive spawning-biomass retrospective pattern define the next evaluation\npriorities. The ESP framework in\n[Appendix 2](#sec-esp-development-framework) organizes the additional\nindicator and mechanism work.\n\n![Conceptual pathways from physical conditions and prey through age-0 condition, overwinter survival, cannibalism, and age-1 recruitment.](assets/model-26-0/dsem-dag.png){#fig-model-26-dsem-dag fig-alt=\"Directed graph in which sea ice affects cold-pool extent, temperature, blooms, and prey. Prey and juvenile abundance affect age-0 energy and overwinter survival. Cold-pool extent and adult-juvenile overlap affect cannibalism. These survival pathways lead to age-1 recruitment. Dashed direct paths connect late-summer SST and cold-pool extent to recruitment for the fitted proxy models.\" width=\"100%\"}\n\n| DSEM specification | Delta AIC | Reduction in unexplained recruitment variation |\n|---|---:|---:|\n| Age-0 late-summer SST | 0.00 | 10.5% |\n| Cold pool + age-0 late-summer SST | 1.63 | 12.0% |\n| No-edge reference | 2.25 | 0.0% |\n| Cold pool | 4.11 | 0.3% |\n\n: Exploratory DSEM comparison using the common data block. {#tbl-model-26-dsem}\n\n![AIC differences among the four current-branch DSEM recruitment models.](assets/model-26-0/dsem_aic_comparison.png){#fig-model-26-dsem-aic fig-alt=\"Horizontal bars compare AIC differences for age-0 late-summer SST, the combined SST and cold-pool model, the no-edge reference, and the cold-pool-only model. The SST-only model has the lowest AIC.\" width=\"76%\"}\n\n```{=latex}\n\\clearpage\n```\n\n| Model | Recruitment pathway | Estimate | 95% interval |\n|---|---|---:|---:|\n| Cold pool | Cold pool | 0.041 | -0.169 to 0.251 |\n| Age-0 late-summer SST | SST | -0.222 | -0.426 to -0.017 |\n| Combined | Cold pool | -0.069 | -0.292 to 0.153 |\n| Combined | SST | -0.254 | -0.484 to -0.024 |\n\n: Standardized direct proxy pathways to age-1 recruitment. {#tbl-model-26-dsem-paths}\n\n![Standardized cold-pool and age-0 SST coefficients for the exploratory DSEM models.](assets/model-26-0/dsem_recruitment_paths.png){#fig-model-26-dsem-paths fig-alt=\"Point estimates and 95-percent intervals compare direct cold-pool and age-0 late-summer SST paths to recruitment. Both SST estimates are negative with intervals below zero. Cold-pool estimates lie near zero with intervals spanning zero.\" width=\"88%\"}\n\n# Conclusion\n\nModel 26.0 provides a reproducible Rceattle implementation of the EBS pollock\nassessment. It closely follows the Model 23.2 bridge, passes the stated\nconvergence and simulated-data recovery checks, carries the assessment state\ninto the standard Tier 3 projection model, and makes the full analysis\navailable through documented R workflows. The whole-index-fleet sensitivities\nshow that BTS supplies the strongest information about population scale and\nfishing mortality, ATS contributes increasingly to recent biomass and\nrecruitment, and AVO provides a smaller complementary signal. These patterns\nare consistent with the roles and lengths of the three survey series.\n\nRceattle is also being used to develop the Gulf of Alaska (GOA) pollock\nassessment, and the companion comparison successfully reran the GOA base model\nthrough its numerical fit checks. The GOA application estimates recruitment\nand changes in survey catchability within the fitted model, whereas the EBS\napplication emphasizes translation of the established ADMB structure and a\nseparate `spmR` projection handoff. Together, the applications show how\nRceattle can support stocks with different survey histories and assessment\nstructures. They also provide a shared basis for pinning software and input\nversions, recording which observations enter each fit, applying common fit and\nretrospective checks, and testing the projection handoff. Stock-specific\nsurveys, age ranges, and selectivity choices remain central to each assessment\nwhile the shared Rceattle platform supports consistent and transparent\nevaluation across both regions.\n\nThe diagnostic results also define a practical operational checklist. The\nproduction run should retain the two-stage fitting sequence and multi-start\nevaluation, repeat the OSA and lag-preserving retrospective analyses, review\nBTS inputs closely, and carry the fitted state into the validated `spmR`\nprojection workflow. The operational specification should keep DSEM disabled\n(`DSEM = NULL`); the environmental pathways and SparseNUTS work remain separate\nresearch evaluations.\n\nThe combined bridge, convergence, self-test, index-sensitivity, retrospective,\nand projection evidence supports a recommendation that the Plan Team and SSC\nadopt Model 26.0 for producing EBS pollock management advice in November and\nDecember 2026. The updated-data run will provide the ABC, OFL, and stock-status\nresults for that review. Model 23.0 provides continuity until the review bodies\ncomplete this transition.\n\n# References {.unnumbered}\n\n::: {#refs}\n:::\n\n# Appendices\n\n## Appendix 1: Main SSC comments and responses {#sec-ssc-comments}\n\nA funding lapse ended preparation of the November and December 2025 EBS\npollock SAFE package. The October 2025 SSC comments therefore carry forward to\nthe 2026 assessment cycle for formal response. The responses below describe\nthe planned work for 2026 and later years.\n\n### Current status\n\n- The next assessment needs to trace the 2025 RTMB starting model back to the\n  2024 ADMB source, along with updated survey data, 2025 FT-NIRS ages, the\n  comparison of traditional and FT-NIRS ages, model names, and the document\n  archive.\n- Work continues on Rceattle, SPoRC, natural mortality, selectivity, and\n  age-composition weighting in response to the SSC comments.\n- Current analyses address Russian catches and the recruitment penalty for the\n  2018 year class.\n- Work on the revised AVO index depends on completion and review of the new\n  uncertainty analysis.\n\nCompletion of an SSC response requires the analysis, results, and explanation\nfor review. Current research contributes evidence toward that completion.\n\n### Comments and responses\n\nThe response matrix pairs each October 2025 SSC comment with the analysis,\ndocumentation, or review action planned for the 2026 assessment cycle.\n\n| SSC comment | Response |\n|---|---|\n| Use the 2024 base model as the source for an RTMB implementation, with routine data updates. | Use the accepted Model 23.0 (ADMB) configuration as the scientific source. First check the direct RTMB translation as Model 23.1, then use Model 25.0 (RTMB) for the assessment line begun in 2025. List each new data set and each model change separately. Save the model version, run files, diagnostics, projections, and management quantities used in the report. |\n| Use the updated Groundfish Assessment Program estimates of survey biomass and age composition. | Add the `sdmTMB` biomass estimates and `tinyVAST` age compositions as updated survey data. Record the data delivery date, software version, model settings, and input files. Compare the old and new survey series and show whether the change affects the assessment results. |\n| Use FT-NIRS age compositions for the 2025 fishery and surveys. | Document how the FT-NIRS ages were produced, screened, grouped, and assigned to fishery and survey data. Record sample sizes and aging-error matrices. Check the final model input against the source data before fitting the assessment. |\n| Compare traditional microscope ages with FT-NIRS ages and show the effects on model results and management quantities. | Run the same assessment with traditional ages, FT-NIRS ages with one aging-error matrix, and FT-NIRS ages with fleet-specific aging-error matrices. Compare cohort patterns, fits to fishery and survey ages, residuals, recruitment, spawning biomass, reference points, ABC, and OFL. Save the full comparison in the assessment appendix and at a permanent web address. |\n| Revisit the revised AVO index after the new uncertainty analysis has been reviewed. | After review of the final uncertainty method, compare the revised point estimates and uncertainty with the current AVO series. Show their effect on model fit, stock estimates, and management quantities before proposing a change to the base model. |\n| Develop a plan with the BSAI Groundfish Plan Team for moving beyond ADMB. | Use the model history and numbering plan above. Compare RTMB, Rceattle, and SPoRC with the same data and a common set of tests. Ask the Plan Team to agree on the tests before selecting the model software for future assessments. Keep the accepted assessment model as the control until a replacement gives stable estimates, sound uncertainty, acceptable retrospective results, and reproducible projections. |\n| Examine the effect of including Russian catches. | First confirm the source, area, years, units, species identification, and uncertainty of the Russian catch estimates. Then run clearly defined catch scenarios. Explain the assumptions about stock movement and population boundaries and show the effects on stock size, reference points, ABC, and OFL. |\n| Explore time-varying natural mortality, selectivity, age-composition weighting, and cohort and temperature effects on weight at age. | Study each topic separately. State the scientific question before fitting a model. For each change, show model fit, parameter uncertainty, retrospective results, projections, and effects on management advice. Keep poorly estimated or unstable models as research results. |\n| Continue work with CEATTLE estimates of natural mortality and consider Rceattle for time-varying mortality. | Test time-varying natural mortality as a sensitivity analysis. Check whether the model can separate mortality changes from recruitment, selectivity, and survey effects. The full set of assessment needs will guide the choice of model software. |\n| Explain how the recruitment penalty affects the estimated 2018 year class and why the likelihood profile favored a larger recruitment estimate. | Prepare a likelihood profile for the 2018 recruitment deviation. Show how the recruitment penalty and each data source change across the profile. Explain which parts of the model favor a larger year class and how the estimate affects spawning biomass, reference points, ABC, and OFL. |\n| Clearly identify the models proposed for the assessment, including model numbers. | Use Model 23.0 (ADMB) for the accepted 2024 source, Model 23.1 (RTMB) for the direct translation check, Model 25.0 (RTMB) for the line begun in 2025, and Model 26.0 (Rceattle) for the line begun in 2026. Use the same short names in the report, presentations, run folders, tables, and archive. For every model, list its purpose, parent model, data set, model changes, software version, and review status. State clearly which model is recommended for management advice. |\n| Archive the October and December SAFE documents and presentations. | Archive the October 2025 material that exists and add a short note explaining that the funding lapse prevented the November and December SAFE package. For future reviews, save the Quarto source, rendered reports, presentations, model files, data list, software versions, and file checksums in one dated release. |\n\n: Responses to the October 2025 SSC comments on EBS pollock. The SSC comments\nare summarized from pages 27 to 29 of the final October 2025 SSC report.\n\n### Earlier responses to 2024 SSC comments\n\n::: {.callout-note title=\"Retained material\"}\nThe responses below were on the previous version of the SSC response page and\nretain their original scientific claims. Confirm these claims against the\ncompleted analyses and assessment record before citing them as final 2025\nresults.\n:::\n\n**Dynamic Species Environment Models (DSEM) and recruitment mechanisms**  \n*The SSC recommended further exploration of DSEM to reconcile contrasting signals such as record larval biomass in 2024, low age-0 abundance, chronically low condition, and increasing adult biomass.*  \n*In 2025, exploratory DSEM analyses continue under the ESR framework and remain outside the current assessment. The Recruitment section presents anomalous recruitment indicators for context.*\n\n> **2026 activity:** The [Rceattle application](https://noaa-afsc.github.io/ebswp_rceattle/) presents the DSEM analysis together with preliminary ESP work.\n\n**Pollock cannibalism index**  \n*The SSC requested extrapolation of the index to biomass consumed.*  \n*For 2025, the index is updated. Work continues toward final biomass-consumed estimates as a development priority.*\n\n**Tier 1 vs. Tier 3 classification**  \n*The SSC supported Tier 3 classification given reliance on priors and limited data at low stock sizes.*  \n*The 2025 assessment maintains Tier 3a status and focuses its calculations on that tier, consistent with SSC guidance.*\n\n**Multispecies model outputs**  \n*The SSC encouraged use of time-varying mortality or consumption estimates from the multispecies model, noting its strategic role in climate planning.*  \n*In 2025, multispecies outputs remain under review for potential use in ESP indicators and future assessment development.*\n\n**Biological observations**  \n*The SSC noted low weight-at-age and condition in recent years and emphasized the importance of the 2018 year class.*  \n*The 2025 BTS confirms condition remains below average. The 2018 year class continues to dominate spawning biomass but shows expected decline as it ages out of the population.*\n\n**Selectivity assumptions**  \n*The SSC supported the use of the five-year moving average selectivity for projections.*  \n*This method is retained in 2025, with updated retrospective diagnostics.*\n\n**Model status and diagnostics**  \n*The SSC endorsed Model 23.0, Tier 3a classification, and ABC equal to the maximum permissible.*  \n*Model 23.0 is retained for 2025 with updated data inputs. Tier 3a status and ABC recommendations remain as supported by the SSC.*\n\n**Additional recommendations**\n\n- *State-space approach (TMB/RTMB):* exploratory work is ongoing.\n- *Russian proportion/movement:* work continues to develop updated estimates.\n- *FT-NIR age validation:* further evaluation continues in preparation for integration.\n- *Recruitment penalty (2018 cohort):* sensitivity analyses are included; discussion of penalty influence is provided.\n\n**Stock-Recruitment relationship**  \n*The SSC noted reduced influence under Tier 3, but stressed unbiased estimation of recruitment deviates and transparent use of steepness priors.*  \n*The recruitment bias correction is set to zero; steepness priors remain meta-analysis based. The 2025 assessment presents the Tier 3 analysis.*\n\n**Documentation request**  \n*The SSC requested that the September 2024 SRR document be included as an appendix or linked.*  \n*The document has been added as Appendix X in this SAFE.*\n\n#### SSC 2024 comments and 2025 responses\n\nThe retained response matrix summarizes how the 2025 work addressed each 2024\nSSC comment and identifies topics that continue into the current cycle.\n\n| SSC comment | 2025 response |\n|---|---|\n| Explore use of DSEM for pollock recruitment anomalies | Recruitment section presents the anomalies; exploratory analyses continue toward future integration. |\n| Extrapolate cannibalism index to biomass consumed | Index updated; extrapolated biomass estimates continue in development toward final review. |\n| Tier 1 vs. Tier 3 classification | Maintained Tier 3a classification and focused calculations on that tier. |\n| Use multispecies model outputs (time-varying M, consumption) | Multispecies outputs remain under review for ESP and future assessment use. |\n| Biological observations (low condition, 2018 year class) | 2025 BTS confirms below-average condition; 2018 cohort still dominant but declining. |\n| Use of five-year moving average selectivity | Retained for 2025 projections; retrospective diagnostics updated. |\n| Endorse Model 23.0, Tier 3a, ABC=max permissible | Continued use of Model 23.0; Tier 3a classification; ABC set equal to maximum permissible. |\n| Recommendations: state-space approach, Russian distribution, FT-NIR, recruitment penalty | State-space exploration and FT-NIR evaluation continue; work is developing updated Russian estimates; sensitivity runs describe the penalty influence. |\n| Stock-recruitment relationship | The 2025 assessment focuses on recruitment deviations with zero bias correction; the steepness prior remains meta-analysis based. |\n| Add Sept 2024 SRR document as appendix | Document included as Appendix X. |\n\n## Appendix 2: Draft EBS pollock ESP development framework {#sec-esp-development-framework}\n\nThis appendix provides a working structure for an eastern Bering Sea pollock\nEcosystem and Socioeconomic Profile (ESP). It separates the concise assessment\ndevelopment results in @sec-model-26-0 from the broader indicator synthesis,\nevidence trail, and update cycle needed for a complete ESP. The headings below\ncan be expanded as current-year ecosystem and socioeconomic products become\navailable.\n\n| ESP component | EBS pollock content | Current development status |\n|---|---|---|\n| Executive summary | Management relevance, principal ecosystem signals, socioeconomic conditions, and key data needs | Complete after the annual indicator assessment |\n| Introduction and justification | Purpose, review history, focal population responses, and intended management use | Initial justification recorded; team review planned |\n| Data | Assessment states, physical indices, plankton and prey indices, age-0 condition, predation and overlap products, and socioeconomic series | Core inventory assembled; biological mediators continue to expand |\n| Indicator synthesis | Life-history table, conceptual pathways, and mechanism table | Draft structure and initial recruitment graph available |\n| Proposed indicators | Small set selected by mechanism, timing, record length, uncertainty, and annual availability | SST and cold pool illustrate the workflow; age-0 energy and prey remain priorities |\n| Indicator assessment | Current condition, trends, uncertainty, and plain-language interpretation | Update with current-year ESP and Ecosystem Status Report products |\n| Indicator analysis | Common-data DSEM comparisons, pathway estimates, prediction checks, and scientific sign checks | Four current-branch DSEM fits presented in Section 5.3 |\n| Data gaps and priorities | Age-0 energy, prey lipid and abundance, bloom-prey timing, overlap, and observation error | Priorities identified for team confirmation and annual production |\n| Conclusion and management use | Role of each indicator in recruitment modeling, risk assessment, or monitoring | Complete after validation and review |\n\n: Proposed EBS pollock ESP structure and present development status.\n{#tbl-esp-appendix-structure}\n\nThe framework assigns every ESP component a purpose and current development\nstatus, keeping the pending annual synthesis and review steps visible\n(@tbl-esp-appendix-structure).\n\n### Executive summary\n\n::: {.callout-note title=\"ESP summary placeholder\"}\nSummarize the current ecosystem and socioeconomic conditions after the annual\nindicator assessment is complete. Distinguish indicators that improve\nprediction from those that provide management context.\n:::\n\n### Introduction and justification\n\nThe ESP will connect ecosystem and fishing-community conditions with the\nassessment quantities used to evaluate pollock status and risk. Age-1\nrecruitment is the initial focal population response because early survival\nlinks physical conditions, prey, age-0 condition, overwinter survival, and\ncannibalism with later assessment observations. The completed ESP should state\nthe management question for every retained indicator.\n\n### Data\n\nThe ESP data inventory will record the source, units, timing, spatial coverage,\nuncertainty, update schedule, and cohort alignment of each candidate series.\nThe inventory includes assessment states; sea ice, temperature, and cold-pool\nindices; plankton and prey; age-0 abundance and condition; predator overlap and\nconsumption; and fishery and community indicators. The common data block used\nfor each statistical comparison will be archived with the results.\n\n### Indicator synthesis\n\nThe life-stage synthesis connects the principal biological processes with the\navailable evidence and the observations needed to strengthen each pathway\n(@tbl-esp-life-history).\n\n| Life stage | Processes emphasized | Current evidence | Priority information need |\n|---|---|---|---|\n| Spawning and eggs | Adult condition, timing, location, egg development, and transport | Adult and physical indices are regularly available | Cohort-specific egg production and transport exposure |\n| Larvae | Bloom timing, prey match, transport, growth, and predation | Physical forcing is available across many years | Annual prey-match and larval-survival indices |\n| Age 0 | Prey amount and quality, growth, distribution, and fall energy | SST is long; prey and condition series are shorter | Consistent fall abundance, diet lipid, energy density, and total energy |\n| Overwinter age 0 to age 1 | Energy reserves, metabolic demand, winter conditions, and predation | Physical proxies and modeled recruitment are available | Direct annual survival observations and uncertainty |\n| Juvenile and pre-recruit | Adult overlap, cannibalism, and other predation | Adult abundance is long; overlap products require timing review | Cohort-aligned overlap and predation mortality |\n| Adult | Spawner abundance, condition, distribution, and cannibalism | Assessment abundance, maturity, and condition are available | Separation of maternal, density, and shared-data pathways |\n\n: Draft life-history synthesis for the EBS pollock ESP.\n{#tbl-esp-life-history}\n\nThe conceptual graph in @fig-model-26-dsem-dag is the initial recruitment\nframework. Each candidate statistical pathway should trace to a stated\nmechanism, cohort timing, expected direction, and documented data source.\n\n### Proposed indicators\n\nCandidate indicators will be screened for a clear biological or socioeconomic\nmechanism, correct seasonal and cohort timing, adequate record length,\nquantified uncertainty, stable annual production, and a defined use in\nassessment or risk evaluation. The initial physical examples are age-0\nlate-summer SST and cold-pool extent. Proximal biological indicators such as\nfall age-0 energy and lipid-rich prey have priority as their annual series\ndevelop.\n\n### Indicator assessment\n\nFor every retained indicator, the annual assessment will show the current\nvalue, historical distribution, trend, uncertainty, and interpretation. A\nshort synthesis will distinguish broad environmental context from evidence\nthat directly informs recruitment, stock status, fishery performance, or\ncommunity exposure.\n\n### Indicator analysis\n\nThe initial common-data DSEM comparison is presented in\n@sec-model-26-0. Future analyses will add terminal-year and blocked prediction,\nalternative cohort timing, observation-error sensitivity, retrospective\nstability, and candidate graphs containing proximal biological mediators.\nCandidate models will retain a common data block so changes in fit reflect the\npathways rather than a changing set of years.\n\n### Data gaps and priorities\n\nThe principal biological priorities are fall age-0 energy, lipid content and\nabundance of key prey, bloom and prey-match timing, juvenile-adult overlap,\npredation mortality, and consistent observation-error estimates. The ESP team\nwill also identify fishery and community indicators with stable annual updates\nand clear links to management questions.\n\n### Conclusion and management use\n\nThe completed ESP will classify each indicator as suitable for recruitment\nmodeling, assessment risk evaluation, socioeconomic context, or continued\nmonitoring. Predictive indicators will require performance checks across\nwithheld years. Contextual indicators will retain value by describing current\nconditions and plausible mechanisms even when they remain outside the\nassessment likelihood.\n\n## Appendix 3: Exploratory SparseNUTS sampling {#sec-sparsenuts}\n\nThis appendix evaluates whether the complete Model 26.0 joint objective can be\nsampled with SparseNUTS. It uses the same 1964--2024 input data and operating\nconfiguration as the maximum-likelihood fit: DSEM is set to `NULL`, recruitment\ndeviations are represented as fixed parameters, and the full set of 1,218 joint\nparameters enters the sampler. The four dense-metric chains each used 1,000\nwarmup iterations followed by 1,000 retained draws, for 4,000 retained draws in\ntotal. The chains began at the converged maximum-likelihood estimates, where\nthe maximum absolute gradient was 0.000077.\n\nThe run completed with zero divergences, zero maximum-tree-depth events, and a\nminimum energy Bayesian fraction of missing information (E-BFMI) of 0.884.\nMinimum tail effective sample size (ESS) was 469. Maximum R-hat was 1.018 and\nminimum bulk ESS was 395; both occurred for `index_log_q[3]` and fall just\noutside the review targets of R-hat at or below 1.01 and bulk ESS at or above\n400. The trace examples show overlapping chains, while the full diagnostic\ndistribution identifies this small group of slower-mixing parameters\n(@fig-model-26-sparsenuts-trace; @fig-model-26-sparsenuts-diagnostics;\n@tbl-model-26-sparsenuts-diagnostics).\n\n**Energy Bayesian fraction of missing information (E-BFMI):** measures how\neffectively momentum resampling moves a Hamiltonian Monte Carlo chain across\nthe energy levels of its joint position-and-momentum distribution. It compares\nthe squared change in total energy between successive iterations with the\noverall variation in energy. In plain language, E-BFMI asks whether each step\nchanges energy enough to explore the posterior landscape. Higher values\nsupport more effective energy exploration. Values below 0.30 are commonly\ntreated as a warning rather than a universal pass-or-fail threshold\n[@betancourt2016cotangent; @betancourt2017hmc]. The [CmdStan diagnostic\nguide](https://mc-stan.org/docs/2_39/cmdstan-guide/diagnose_utility.html) uses\n0.30 as its nominal warning threshold.\n\nThe six parameters with the lowest bulk ESS were `index_log_q[3]`, `log_F[2]`,\n`log_F[3]`, `log_F[8]`, `log_F[4]`, and `log_F[9]`. Their marginal and joint\nposterior distributions, pairwise correlations, maximum-likelihood estimates,\nand Hessian-based correlation ellipses are shown in\n@fig-model-26-sparsenuts-slowest-pairs. The uncertainty comparison in\n@fig-model-26-sparsenuts-uncertainty compares posterior standard deviations\nfrom the retained draws with local asymptotic standard errors derived from the\nmaximum-likelihood Hessian for all 1,218 parameters. The dashed one-to-one line\nmarks agreement between the two uncertainty summaries. The pairwise posterior\ncorrelations among the six slowest-mixing parameters range from 0.82 to 0.93.\nAcross all parameters, the log-scale correlation between MCMC and Hessian\nuncertainty is 0.971, and the median ratio of MCMC standard deviation to\nHessian standard error is 1.006. The corresponding ratios for the six slowest\nparameters range from 1.45 to 1.63. Differences from the one-to-one line can\nreflect posterior shape as well as sampling behavior, so this figure is\ninterpreted together with R-hat, ESS, trace, and pairs diagnostics.\n\nThese results demonstrate that the complete joint objective can be sampled on\nfour local cores. Additional retained draws and focused review of the index\ncatchability parameters will strengthen the uncertainty summary. The\nSparseNUTS results therefore remain an exploratory evaluation and are separate\nfrom the maximum-likelihood Model 26.0 results proposed for management advice.\nThe complete 87-MB fit object is retained in the local analysis results\ndirectory, while this report carries only compact diagnostic tables and\nfigures. Script [M26-10](scripts/model-26-0/run_model_26_sparsenuts_5_23.R)\nreproduces the run from the saved Model 26.0 fit.\n\n![Retained SparseNUTS draws for four representative Model 26.0 parameters.](assets/model-26-0/model_26_0_sparsenuts_trace.png){#fig-model-26-sparsenuts-trace fig-alt=\"Four vertically arranged trace plots show overlapping retained draws from four SparseNUTS chains for a recruitment deviation, mean recruitment, and two selectivity deviations. The chains occupy common ranges without sustained separation.\" width=\"88%\"}\n\n![Distributions of R-hat, bulk ESS, and tail ESS across the 1,218 sampled parameters.](assets/model-26-0/model_26_0_sparsenuts_diagnostics.png){#fig-model-26-sparsenuts-diagnostics fig-alt=\"Three vertically arranged histograms summarize R-hat, bulk effective sample size, and tail effective sample size across 1,218 Model 26.0 parameters. Most R-hat values lie close to one, while a small number extend above 1.01. Most effective sample sizes are well above 400.\" width=\"78%\"}\n\n![Joint posterior relationships for the six Model 26.0 parameters with the lowest bulk effective sample sizes. Diagonal panels report bulk ESS and R-hat; upper panels report posterior correlations; and lower panels show retained draws in blue, the maximum-likelihood estimate as a red point, and the local 95% Hessian ellipse in red.](assets/model-26-0/model_26_0_sparsenuts_slowest_pairs.png){#fig-model-26-sparsenuts-slowest-pairs fig-alt=\"A six-by-six pairs display for index log catchability parameter 3 and fishing-mortality parameters 2, 3, 8, 4, and 9. Diagonal panels show posterior histograms with bulk effective sample size and R-hat. Lower panels show retained MCMC draws, maximum-likelihood estimates, and Hessian-based 95 percent ellipses. Upper panels show pairwise posterior correlations ranging from 0.82 to 0.93.\" width=\"94%\"}\n\n![MCMC posterior standard deviations compared with Hessian-based asymptotic standard errors for all 1,218 Model 26.0 parameters.](assets/model-26-0/model_26_0_sparsenuts_uncertainty_comparison.png){#fig-model-26-sparsenuts-uncertainty fig-alt=\"Log-scale scatterplot comparing MCMC posterior standard deviation on the horizontal axis with Hessian-based asymptotic standard error on the vertical axis for 1,218 parameters. A dashed diagonal marks equal uncertainty. The six parameters with the lowest bulk effective sample sizes are highlighted and labeled.\" width=\"78%\"}\n\n| Diagnostic | Result | Review target | Outcome |\n|---|---:|---:|---|\n| Chains | 4 | 4 | Pass |\n| Warmup iterations per chain | 1,000 | 1,000 | Pass |\n| Retained draws per chain | 1,000 | 1,000 | Pass |\n| Maximum R-hat | 1.018 | 1.01 or lower | Review |\n| Minimum bulk ESS | 395 | 400 or higher | Review |\n| Minimum tail ESS | 469 | 400 or higher | Pass |\n| Divergences | 0 | 0 | Pass |\n| Maximum-tree-depth events | 0 | 0 | Pass |\n| Minimum E-BFMI | 0.884 | above 0.30 | Pass |\n\n: SparseNUTS configuration and sampling diagnostics for the complete Model 26.0 joint objective. {#tbl-model-26-sparsenuts-diagnostics}\n\n## Appendix 4: Reproducible model run methods {#sec-model-run-methods}\n\nThe model workflow keeps the editable report and analysis code under version\ncontrol while storing large fit objects in the local analysis repository. The\nRceattle library is pinned to version 5.23.0 from commit\n`adf22f84b399e84e3b9a707e0b3bbb1624179a27` on the\n`dsem-v5-integration` branch. This preserves the exact model code used for the\nresults. Each script checks the expected package version before fitting. The\nbase assessment specification uses the established nonparametric selectivity,\nomits the two-dimensional age-by-year AR1 option, sets DSEM to `NULL`, and\nretains recruitment deviations as fixed parameters.\n\nThe following sequence reproduces the analysis. First, install the pinned\nRceattle revision and afscOSA 0.0.1 in an isolated R library. Second, run\nM23-01 when the ADMB-to-Rceattle translation check needs rebuilding. Third,\nfrom the analysis repository, run M26-01; it reads the 1964--2024 assessment\nworkbook, fits the model in two stages, saves the complete fit locally, and\ncreates the bridge, OSA, and jitter products. Fourth, run M26-02 through\nM26-04 for the self-test and lag-preserving retrospective evaluations. Fifth,\nrun M26-09 and M26-11 for whole-index and sampling-event influence. Sixth, run\nM26-05 followed by M26-06 for the `spmR` projection handoff. Finally, run the\nresearch evaluations M26-07 and M26-10 separately from the operational fit,\nthen run M26-12 to summarize the retained SparseNUTS draws.\n\nThe shell pattern below makes the analysis and report locations explicit. The\nscripts write complete fit objects beneath the analysis repository's\n`results/` directory and compact report products beneath the report source\ntree.\n\n\n::: {.cell}\n\n:::\n\n\nThe script register in @tbl-model-26-script-register gives the stable ID,\npurpose, input, and output for every step. These IDs provide a short reference\nfor reruns, review notes, and archived products.\n\n\n::: {#tbl-model-26-script-register .cell tbl-cap='Model 23.2 bridge and Model 26.0 script register.'}\n::: {.cell-output-display}\n\n\n| Step|Script ID |Script                                             |Purpose                                                                                   |\n|----:|:---------|:--------------------------------------------------|:-----------------------------------------------------------------------------------------|\n|    1|M23-01    |[run_model_23_0_vs_23_2_admb_comparison.R](scripts/model-26-0/run_model_23_0_vs_23_2_admb_comparison.R)|Rebuild and compare the original and Rceattle-aligned ADMB bridge runs                    |\n|    2|M26-01    |[run_model_26_rceattle_5_23.R](scripts/model-26-0/run_model_26_rceattle_5_23.R)|Fit the two-stage Model 26.0 base and create bridge OSA and jitter diagnostics            |\n|    3|M26-02    |[run_model_26_self_test_5_23.R](scripts/model-26-0/run_model_26_self_test_5_23.R)|Simulate and refit the configured model for parameter and state recovery                  |\n|    4|M26-03    |[run_model_26_retrospective_sensitivity_5_23.R](scripts/model-26-0/run_model_26_retrospective_sensitivity_5_23.R)|Run nine peels with stream-specific data lags and terminal selectivity treatment          |\n|    5|M26-04    |[run_model_26_retrospective_data_sensitivity_5_23.R](scripts/model-26-0/run_model_26_retrospective_data_sensitivity_5_23.R)|Test observation blocks responsible for the 2020--2021 retrospective transition           |\n|    6|M26-09    |[run_model_26_index_series_sensitivity_5_23.R](scripts/model-26-0/run_model_26_index_series_sensitivity_5_23.R)|Refit after removing the complete BTS ATS or AVO fleet contribution while retaining CPUE  |\n|    7|M26-05    |[write_spmr_projection_inputs.R](scripts/model-26-0/write_spmr_projection_inputs.R)|Translate the fitted population state and biological schedules into SPM files             |\n|    8|M26-06    |[run_model_26_spmr_projection_5_23.R](scripts/model-26-0/run_model_26_spmr_projection_5_23.R)|Run and summarize the seven Tier 3 projection alternatives                                |\n|    9|M26-07    |[run_model_26_dsem_5_23_pathways.R](scripts/model-26-0/run_model_26_dsem_5_23_pathways.R)|Fit the separate exploratory recruitment-pathway models                                   |\n|   10|M26-10    |[run_model_26_sparsenuts_5_23.R](scripts/model-26-0/run_model_26_sparsenuts_5_23.R)|Sample the complete joint Model 26.0 objective with four dense-metric chains              |\n|   11|M26-11    |[run_model_26_case_deletion_5_23.R](scripts/model-26-0/run_model_26_case_deletion_5_23.R)|Build the observation schedule and refit after deleting selected complete sampling events |\n|   12|M26-12    |[plot_model_26_sparsenuts_diagnostics.R](scripts/model-26-0/plot_model_26_sparsenuts_diagnostics.R)|Create pairs and uncertainty-comparison diagnostics from the retained SparseNUTS draws    |\n\n\n:::\n:::\n\n\n## Appendix 5: Observation continuity and case-deletion influence {#sec-observation-influence}\n\nThis diagnostic separates whether an observation was available and used from\nhow much the accepted fit changes when a fitted sampling event is removed. The\nobservation-continuity panel uses an explicit assessment-input schedule: annual\nfor the fishery, BTS, and AVO rows and even years for ATS rows. Years after\n2024 are shown only to distinguish the current fitted span; the schedule does\nnot imply a commitment about future field operations.\n\nThe continuity panel distinguishes events present in the Model 26.0 input,\nscheduled events that are absent, years outside a row's fitted span, and years\nafter the terminal fitted year (@fig-model-26-observation-continuity). It also\nshows where age-1 proportions are fitted separately from the main age\ncomposition. This makes survey timing, composition coverage, and recent gaps\nvisible without treating the schedule as a prediction.\n\nThe case-deletion analysis removes an entire fitted index observation or\ncomposition row for one selected fleet-year event and then refits the complete\nmodel. All 12 refits reached convergence status OK with positive-definite\nHessians. The 2024 BTS biomass index had the largest terminal spawning biomass\neffect (-5.29%) and lowered terminal age-1 recruitment by 25.33%. Removing the\n2024 ATS age composition lowered terminal spawning biomass by 2.64% and raised\nterminal recruitment by 25.35%; its largest recruitment change across all\nyears was 53.93%. Removing the 2024 AVO index raised terminal spawning biomass\nby 5.05% and terminal recruitment by 5.87%. Other selected events produced\nsmaller terminal changes (@fig-model-26-case-deletion; @tbl-model-26-case-deletion).\n\nThese values describe influence within the current fitted model. Decisions\nabout observation weighting draw on the full data-quality record, sampling\ndesign, fit diagnostics, and biological interpretation. Script\n[M26-11](scripts/model-26-0/run_model_26_case_deletion_5_23.R) creates the\nexplicit schedule, refits the selected cases, and saves each compact checkpoint\nlocally.\n\n![Observation continuity for fishery, BTS, ATS, and AVO inputs from 2014 through 2026.](assets/model-26-0/model_26_0_observation_continuity.png){#fig-model-26-observation-continuity fig-alt=\"A grid lists years 2014 through 2026 across rows for fishery, bottom-trawl survey, acoustic-trawl survey, and acoustic vessel-of-opportunity data types. Symbols distinguish fitted observations, scheduled gaps, years outside the fitted span, and years after 2024. Fishery, BTS, and AVO schedules are annual, while ATS schedules use even years.\" width=\"100%\"}\n\n![Influence of selected sampling-event deletions on terminal spawning biomass and age-1 recruitment.](assets/model-26-0/model_26_0_case_deletion_influence.png){#fig-model-26-case-deletion fig-alt=\"Two horizontal dot plots show percent changes in terminal spawning biomass and terminal age-1 recruitment after 12 selected sampling events are deleted one at a time. The 2024 BTS biomass index, 2024 ATS age composition, and 2024 AVO index have the largest terminal effects.\" width=\"92%\"}\n\n\n::: {#tbl-model-26-case-deletion .cell tbl-cap='Influence of selected sampling-event deletions on terminal Model 26.0 spawning biomass and recruitment.'}\n::: {.cell-output-display}\n\n\n|Sampling event removed   | Terminal SSB change (%)| Terminal recruitment change (%)| Largest recruitment change (%)|\n|:------------------------|-----------------------:|-------------------------------:|------------------------------:|\n|Fishery composition 2020 |                   +0.22|                           +0.76|                          14.50|\n|Fishery composition 2023 |                   -2.33|                           +2.04|                          11.81|\n|BTS biomass index 2021   |                   +1.26|                           -0.87|                           1.39|\n|BTS biomass index 2024   |                   -5.29|                          -25.33|                          25.33|\n|BTS age composition 2021 |                   +0.83|                           +0.22|                           7.48|\n|BTS age composition 2024 |                   +0.86|                           -1.28|                          15.70|\n|ATS biomass index 2024   |                   +1.65|                           +1.54|                           2.47|\n|ATS age composition 2020 |                   +0.30|                           -0.11|                           0.33|\n|ATS age composition 2024 |                   -2.64|                          +25.35|                          53.93|\n|ATS age-1 index 2022     |                   +1.29|                           +2.27|                           8.64|\n|AVO index 2021           |                   -0.35|                           +0.31|                           0.56|\n|AVO index 2024           |                   +5.05|                           +5.87|                           9.79|\n\n\n:::\n:::\n\n\n## Appendix 6: Glossary of acronyms {#sec-glossary}\n\nThis glossary follows the ASAR package convention of maintaining one\nalphabetical source table with `Label`, `Acronym`, and `Meaning` fields. The\nlabel provides a stable key for document automation, while the acronym and\nmeaning provide the reader-facing text. The report-specific source file can be\nupdated once and reused in future output formats (@tbl-acronym-glossary).\n\n\n::: {#tbl-acronym-glossary .cell tbl-cap='Acronyms used in the September 2026 assessment developments report.'}\n::: {.cell-output-display}\n\n\n|   |Acronym    |Meaning                                                                                    |\n|:--|:----------|:------------------------------------------------------------------------------------------|\n|1  |ABC        |acceptable biological catch                                                                |\n|2  |ADMB       |Automatic Differentiation Model Builder                                                    |\n|3  |AFSC       |Alaska Fisheries Science Center                                                            |\n|4  |AI         |artificial intelligence                                                                    |\n|5  |AIC        |Akaike information criterion                                                               |\n|6  |AR1        |first-order autoregressive structure                                                       |\n|7  |ATS        |acoustic-trawl survey                                                                      |\n|8  |AVO        |acoustic vessel-of-opportunity                                                             |\n|9  |B35%       |spawning biomass reference point associated with 35 percent of unfished spawning potential |\n|10 |B40%       |spawning biomass reference point associated with 40 percent of unfished spawning potential |\n|11 |BSAI       |Bering Sea and Aleutian Islands                                                            |\n|12 |BTS        |bottom-trawl survey                                                                        |\n|13 |CEATTLE    |Climate-enhanced Age-based model with Temperature-specific Trophic Linkages and Energetics |\n|14 |CPUE       |catch per unit effort                                                                      |\n|15 |DSEM       |dynamic species environment model                                                          |\n|16 |E-BFMI     |energy Bayesian fraction of missing information                                            |\n|17 |EBS        |eastern Bering Sea                                                                         |\n|18 |ESP        |Ecosystem and Socioeconomic Profile                                                        |\n|19 |ESR        |Ecosystem Status Report                                                                    |\n|20 |ESS        |effective sample size                                                                      |\n|21 |FT-NIR     |Fourier-transform near-infrared method                                                     |\n|22 |FT-NIRS    |Fourier-transform near-infrared spectroscopy                                               |\n|23 |GOA        |Gulf of Alaska                                                                             |\n|24 |HMC        |Hamiltonian Monte Carlo                                                                    |\n|25 |ISS        |input sample size                                                                          |\n|26 |LR         |likelihood ratio                                                                           |\n|27 |MCMC       |Markov chain Monte Carlo                                                                   |\n|28 |MLE        |maximum-likelihood estimate                                                                |\n|29 |NLL        |negative log likelihood                                                                    |\n|30 |NOAA       |National Oceanic and Atmospheric Administration                                            |\n|31 |NPFMC      |North Pacific Fishery Management Council                                                   |\n|32 |NUTS       |no-U-turn sampler                                                                          |\n|33 |OFL        |overfishing limit                                                                          |\n|34 |OSA        |one-step-ahead                                                                             |\n|35 |Q-Q        |quantile-quantile                                                                          |\n|37 |R-hat      |rank-normalized potential scale-reduction statistic                                        |\n|36 |Rceattle   |R implementation of CEATTLE                                                                |\n|38 |RTMB       |R Template Model Builder                                                                   |\n|39 |SAFE       |Stock Assessment and Fishery Evaluation                                                    |\n|40 |SDNR       |standard deviation of normalized residuals                                                 |\n|41 |SparseNUTS |sparse-matrix implementation of the no-U-turn sampler                                      |\n|42 |SPM        |Standard Projection Model                                                                  |\n|43 |SPR        |spawning potential ratio                                                                   |\n|44 |SRR        |stock-recruit relationship                                                                 |\n|45 |SSB        |spawning stock biomass                                                                     |\n|46 |SSC        |Scientific and Statistical Committee                                                       |\n|47 |SST        |sea-surface temperature                                                                    |\n|48 |TMB        |Template Model Builder                                                                     |\n\n\n:::\n:::\n\n\n## Appendix 7: Fishery length frequency patterns {#sec-length-frequency-patterns}\n\nThis appendix summarizes exploratory seasonal and spatial patterns in observed\npollock length-frequency samples. Its scope is exploratory description;\nassessment-model tests belong in separate analyses. The source analysis\nincludes pollock observations from 1991\nonward, excludes observations below 20 cm, and accumulates fish 65 cm and\nlonger in a 65-cm-plus group. Length frequencies are normalized within each\ndisplayed year and grouping. A season includes samples collected before June\n20; B season data are from June 20 onward. Earlier years appear at the top of\neach figure.\n\n### Change from 2025 to 2026\n\nThe observed length distribution shifted toward smaller fish from 2025 to\n2026. Across seasons, mean sampled length declined from 46.17 to 44.81 cm,\nwhile the median remained 46 cm. The percentage longer than 46 cm decreased\nfrom 46.40% to 43.96%, and the percentage at or below 35 cm increased from\n4.03% to 9.86%.\n\nThe shift occurred primarily in the B-season samples. B-season mean length\ndeclined from 45.93 cm in 2025 to 42.55 cm in 2026, and the median declined\nfrom 46 to 43 cm. The proportion longer than 46 cm decreased from 48.90% to\n34.76%, while the proportion at or below 35 cm increased from 6.79% to 17.54%.\nBoth B-season area groups shifted toward smaller fish. In the western group\n(`NMFS_AREA > 519`), mean length declined from 44.26 to 39.39 cm and the\npercentage at or below 35 cm increased from 9.86% to 29.24%. In the eastern\ngroup (`NMFS_AREA < 520`), mean length declined from 48.55 to 45.62 cm and the\npercentage longer than 46 cm decreased from 70.13% to 49.88%.\n\nThe A-season change was smaller and differed in shape. Mean length declined\nfrom 46.39 to 45.82 cm and the median remained 46 cm, while the percentages\nlonger than 46 cm and at or below 35 cm both increased. This indicates greater\nrepresentation in the tails of the sampled A-season distribution in 2026.\nSample coverage also changed: the A-season count increased from 91,912 to\n101,038 observations, whereas the B-season count decreased from 80,749 to\n45,057. These are unstandardized sample distributions, so the differences\ndescribe the available observations and may reflect changes in sampling as\nwell as changes in the fish encountered by the fishery.\n\n### A- and B-season distributions\n\nThe seasonal distributions show the larger 2026 shift toward smaller fish in\nthe B season and the broader-tailed A-season pattern\n(@fig-appendix-lf-seasons).\n\n![Pollock length-frequency proportions by season. The left panel shows samples collected before June 20; the right panel shows samples collected from June 20 onward.](assets/appendices/fig-lf-seasons.png){#fig-appendix-lf-seasons fig-alt=\"Two-panel ridge plot of annual pollock length-frequency proportions from 1991 onward. A-season distributions before June 20 appear in the left panel and B-season distributions from June 20 onward appear in the right. Each row represents one year; a dashed vertical line marks 46 cm and a blue pie wedge gives the percentage longer than 46 cm.\"}\n\n### Combined-season distributions\n\nThe combined-season series places the 2026 increase in fish at or below 35 cm\nwithin the longer record of annual sample distributions\n(@fig-appendix-lf-combined).\n\n![Pollock length-frequency proportions across both seasons.](assets/appendices/fig-lf-combined.png){#fig-appendix-lf-combined fig-alt=\"Ridge plot of annual pollock length-frequency proportions across A and B seasons from 1991 onward. Each row represents one year; a dashed vertical line marks 46 cm and a blue pie wedge gives the percentage longer than 46 cm.\"}\n\n### B-season distributions by NMFS area\n\nThe B-season area comparison shows a stronger shift toward smaller fish in the\nwestern group, while the eastern group retains a larger share above 46 cm\n(@fig-appendix-lf-b-season-area).\n\n![B-season pollock length-frequency proportions by NMFS area group. Samples were collected from June 20 onward. The left panel represents samples west of 170 degrees W; the right panel represents samples east of 170 degrees W, approximately west and east of the Pribilof Islands.](assets/appendices/fig-lf-b-season-area.png){#fig-appendix-lf-b-season-area fig-alt=\"Two-panel ridge plot of annual B-season pollock length-frequency proportions from June 20 onward for 1991 through 2026, divided into areas west and east of 170 degrees W. Each row represents one year; a dashed vertical line marks 46 cm and a blue pie wedge gives the percentage longer than 46 cm.\"}\n\n",
    "supporting": [
      "EBSpollock_Sept_2026_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}